### ISSUE TITLE
One of our mostly harmless robots seems to think you are not a human.

### ISSUE THREAD

**Issue by ipengyo** [huluoyang/freecodecamp.cn#103]
One of our mostly harmless robots seems to think you are not a human.
Because of that, it’s hidden your profile from the public. If you really are human, please contact support to have your profile reinstated. We promise we won’t require DNA proof of your humanity.

Need help with the huluoyang/freecodecamp.cn project?
You could get in contact with @huluoyang. You could open an issue or send them an email.

**Comment by huluoyang** [comment]
GitHub有非常严格的反垃圾和机器人机制。
你通过自己的邮箱给GitHub官方客服发一封邮件即可，证明你不是机器人。
GitHub随后就会解封你的账号。
祝你好运

**Comment by hhsadiq** [comment]
I also got this exact problem. They blocked my profile from public. I reported this problem at support and profile was restored in less than half an hour. I think github guys have programmed their NOT SO HARMLESS robot with some weird too-strict rules. They definitely need to revise their policy, it is giving too many false positives.

**Comment by A-Syntax** [comment]
Just got flagged myself, the last thing I did was create an issue with a question about updating a wiki with a better explanation the context of the initial post was a copy of a response in another issue which I responded to.
