### ISSUE TITLE
"3" is ok

### ISSUE THREAD

**Issue by senvsen** [huluoyang/freecodecamp.cn#108]
Challenge [Modify Array Data With Indexes](https://freecodecamp.cn/challenges/modify-array-data-with-indexes#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0AourArray%5B1%5D%20%3D%203%3B%20%2F%2F%20ourArray%20now%20equals%20%5B1%2C3%2C3%5D.%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B1%2C2%2C3%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyArray%5B0%5D%20%3D%20%223%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
// 举例
var ourArray = [1,2,3];
ourArray[1] = 3; // ourArray now equals [1,3,3].

// Setup
var myArray = [1,2,3];

// Only change code below this line.
myArray[0] = "3";


```

**Comment by huluoyang** [comment]
你好，你的代码是正确的。
不明白你遇到什么问题了？

**Comment by senvsen** [comment]
【myArray[0] = "3";】我这么写的话，myArray 数组就变成["3",2,3]，
开始我以为只能写成【myArray[0] = 3;】

**Comment by huluoyang** [comment]
`myArray[0] = 3;`
`myArray[0] = "3";`
都可以测试通过，应该是测试用例只用了==而没有使用===。
感谢反馈，虽然是个不容易被发现的小问题，但还是应该给你点个赞^_^。
