### ISSUE TITLE
国内访问慢

### ISSUE THREAD

**Issue by shangxinbo** [huluoyang/freecodecamp.cn#109]
rt

**Comment by huluoyang** [comment]
我的感受和你一样，但有些人却觉得快些。
国内的延迟和稳定性好些，但固定1M带宽和传统云盘限制了网站的性能。
国外的千M带宽和SSD硬盘，网站性能好些，但延迟和稳定性差。
多谢你的反馈，后续有新的进展会第一时间告诉你。
