### ISSUE TITLE
能不能在问题底下用中文？它是英文的

### ISSUE THREAD

**Issue by xuan1wo2** [huluoyang/freecodecamp.cn#110]
Challenge [Get JSON with the jQuery getJSON Method](https://www.freecodecamp.cn/challenges/get-json-with-the-jquery-getjson-method) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function(){
      // Only change code below this line.



      // Only change code above this line.
    });

  });
</script>

<div class="container-fluid">
  <div class = "row text-center">
    <h2>Cat Photo Finder</h2>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12 well message">
      The message will go here
    </div>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12">
      <button id = "getMessage" class = "btn btn-primary">
        Get Message
      </button>
    </div>
  </div>
</div>

```

**Comment by huluoyang** [comment]
感谢反馈。
测试部分的文本难度都不高，容易看懂。
当然翻译了会更好。
翻译是个艺术活，翻译的半生不熟还不如不翻译。
如果你英文OK，也欢迎你参与进来翻译。
