### ISSUE TITLE
第六个结果：makeFriendlyDates(["2022-09-05", "2023-09-04"]) 应返回 ["September 5th","September 4th"].

### ISSUE THREAD

**Issue by xm-18y** [huluoyang/freecodecamp.cn#112]
Challenge [Friendly Date Ranges](https://www.freecodecamp.cn/challenges/friendly-date-ranges#?solution=function%20makeFriendlyDates%28arr%29%20%7B%0A%20%20var%20month%3D%5B%22January%22%2C%22February%22%2C%22March%22%2C%22April%22%2C%22May%22%2C%22June%22%2C%22July%22%2C%22August%22%2C%22September%22%2C%22October%22%2C%22November%22%2C%22December%22%5D%3B%0A%20%20var%20dat%3D%5B%22st%22%2C%22nd%22%2C%22rd%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%2C%22th%22%5D%3B%0A%20%20var%20d1%3Darr%5B0%5D.split%28%22-%22%29%3B%0A%20%20var%20d2%3Darr%5B1%5D.split%28%22-%22%29%3B%0A%0A%20%20if%28parseInt%28d1%5B0%5D%29%3D%3DparseInt%28d2%5B0%5D%29%29%7B%0A%20%20%20%20if%28d1%5B1%5D%3D%3Dd2%5B1%5D%29%7B%0A%20%20%20%20%20%20if%28d1%5B2%5D%3D%3Dd2%5B2%5D%29%7B%0A%20%20%20%20%20%20%20%20return%20%5Bmonth%5BparseInt%28d1%5B1%5D%29-1%5D%2B%22%20%22%2BparseInt%28d1%5B2%5D%29%2Bdat%5BparseInt%28d1%5B2%5D%29-1%5D%2B%22%2C%20%22%2Bd1%5B0%5D%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20return%20%5Bmonth%5BparseInt%28d1%5B1%5D%29-1%5D%2B%22%20%22%2BparseInt%28d1%5B2%5D%29%2Bdat%5BparseInt%28d1%5B2%5D%29-1%5D%2CparseInt%28d2%5B2%5D%29%2Bdat%5BparseInt%28d2%5B2%5D%29-1%5D%5D%3B%0A%20%20%20%20%7Delse%7B%0A%20%20%20%20%20%20return%20%5Bmonth%5BparseInt%28d1%5B1%5D%29-1%5D%2B%22%20%22%2BparseInt%28d1%5B2%5D%29%2Bdat%5BparseInt%28d1%5B2%5D%29-1%5D%2B%22%2C%20%22%2Bd1%5B0%5D%2Cmonth%5BparseInt%28d2%5B1%5D%29-1%5D%2B%22%20%22%2BparseInt%28d2%5B2%5D%29%2Bdat%5BparseInt%28d2%5B2%5D%29-1%5D%5D%3B%0A%20%20%20%20%7D%0A%20%20%7Delse%20if%28parseInt%28d2%5B0%5D%29-parseInt%28d1%5B0%5D%29%3D%3D1%20%26%26%20%28%28parseInt%28d2%5B1%5D%29-parseInt%28d1%5B1%5D%29%29%3C0%20%7C%7C%20%28%28parseInt%28d2%5B1%5D%29-parseInt%28d1%5B1%5D%29%29%3D%3D%3D0%20%26%26%20%28parseInt%28d2%5B2%5D%29-parseInt%28d1%5B2%5D%29%29%3C0%29%29%29%7B%0A%20%20%20%20%20%20return%20%5Bmonth%5BparseInt%28d1%5B1%5D%29-1%5D%2B%22%20%22%2BparseInt%28d1%5B2%5D%29%2Bdat%5BparseInt%28d1%5B2%5D%29-1%5D%2Cmonth%5BparseInt%28d2%5B1%5D%29-1%5D%2B%22%20%22%2BparseInt%28d2%5B2%5D%29%2Bdat%5BparseInt%28d2%5B2%5D%29-1%5D%5D%3B%0A%20%20%20%20%7Delse%7B%0A%20%20%20%20%20%20return%20%5Bmonth%5BparseInt%28d1%5B1%5D%29-1%5D%2B%22%20%22%2BparseInt%28d1%5B2%5D%29%2Bdat%5BparseInt%28d1%5B2%5D%29-1%5D%2B%22%2C%20%22%2Bd1%5B0%5D%2Cmonth%5BparseInt%28d2%5B1%5D%29-1%5D%2B%22%20%22%2BparseInt%28d2%5B2%5D%29%2Bdat%5BparseInt%28d2%5B2%5D%29-1%5D%2B%22%2C%20%22%2Bd2%5B0%5D%5D%3B%0A%20%20%20%20%7D%0A%7D%0A%0AmakeFriendlyDates%28%5B%222022-09-05%22%2C%20%222023-09-04%22%5D%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function makeFriendlyDates(arr) {
  var month=["January","February","March","April","May","June","July","August","September","October","November","December"];
  var dat=["st","nd","rd","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th","th"];
  var d1=arr[0].split("-");
  var d2=arr[1].split("-");

  if(parseInt(d1[0])==parseInt(d2[0])){
    if(d1[1]==d2[1]){
      if(d1[2]==d2[2]){
        return [month[parseInt(d1[1])-1]+" "+parseInt(d1[2])+dat[parseInt(d1[2])-1]+", "+d1[0]];
      }
      return [month[parseInt(d1[1])-1]+" "+parseInt(d1[2])+dat[parseInt(d1[2])-1],parseInt(d2[2])+dat[parseInt(d2[2])-1]];
    }else{
      return [month[parseInt(d1[1])-1]+" "+parseInt(d1[2])+dat[parseInt(d1[2])-1]+", "+d1[0],month[parseInt(d2[1])-1]+" "+parseInt(d2[2])+dat[parseInt(d2[2])-1]];
    }
  }else if(parseInt(d2[0])-parseInt(d1[0])==1 && ((parseInt(d2[1])-parseInt(d1[1]))<0 || ((parseInt(d2[1])-parseInt(d1[1]))===0 && (parseInt(d2[2])-parseInt(d1[2]))<0))){
      return [month[parseInt(d1[1])-1]+" "+parseInt(d1[2])+dat[parseInt(d1[2])-1],month[parseInt(d2[1])-1]+" "+parseInt(d2[2])+dat[parseInt(d2[2])-1]];
    }else{
      return [month[parseInt(d1[1])-1]+" "+parseInt(d1[2])+dat[parseInt(d1[2])-1]+", "+d1[0],month[parseInt(d2[1])-1]+" "+parseInt(d2[2])+dat[parseInt(d2[2])-1]+", "+d2[0]];
    }
}

makeFriendlyDates(["2022-09-05", "2023-09-04"]);
//应返回 ["September 5th","September 4th"].

```

**Comment by huluoyang** [comment]
你好，感谢你的反馈。
2022年不是当前年份，所以年份不能忽略。
"2022-09-05" 和 "2023-09-04" 相差不到一年，所以2023可以忽略。
所以正确的结果应该是：["September 5th, 2022","September 4th"]
