### ISSUE TITLE
我的没有图片看不懂

### ISSUE THREAD

**Issue by 1733094103** [huluoyang/freecodecamp.cn#114]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.cn/challenges/inform-with-the-paragraph-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0AHello%20woeld%0A%3Ch2%3Ehello%20paragraph%3Ch2%2F%3Ep) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<h1>Hello World</h1>
<h2>我家的猫咪</h2>
Hello woeld
<h2>hello paragraph<h2/>p
```

**Comment by huluoyang** [comment]
这节本身就没有图片，看懂题目要求就能搞懂了。

```
<h1>Hello World</h1>
<h2>我家的猫咪</h2>
<p>hello paragraph</p>
```
