### ISSUE TITLE
kbd 

### ISSUE THREAD

**Issue by 1733094103** [huluoyang/freecodecamp.cn#115]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.cn/challenges/inform-with-the-paragraph-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0Ap%3Ch3%3Ehello%20paragraph%3Ch3%2F%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<h1>Hello World</h1>
<h2>我家的猫咪</h2>
p<h3>hello paragraph<h3/>
```

**Comment by huluoyang** [comment]
看清题目要求，副标题下面创建一个段落，段落的文本为：hello paragraph
h1：主标题
h2：副标题
p：  段落
