### ISSUE TITLE
关闭debug

### ISSUE THREAD

**Issue by Samtoto** [huluoyang/freecodecamp.cn#116]
https://freecodecamp.cn/email-signup
email: xxx@xxx.com‘
pwd: xxx
![qq 20160708162351](https://cloud.githubusercontent.com/assets/5435818/16681624/73abeae6-4528-11e6-9b45-eb0b9885afbe.png)

**Comment by huluoyang** [comment]
目前只支持GitHub登录，不支持邮箱注册。
感谢反馈，后期会添加邮箱注册方式的。
我也会第一时间通知你。
