### ISSUE TITLE
不会啊怎么做

### ISSUE THREAD

**Issue by 1733094103** [huluoyang/freecodecamp.cn#117]
[Challenge](url) [Uncomment HTML](https://www.freecodecamp.cn/challenges/uncomment-html#?solution=--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A--%3E%0A%3Ch2%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A--%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
-->
<h1>Hello World</h1>
-->
<h2>我家的猫咪</h2>
-->
<p>Hello Paragraph</p>
```

**Comment by huluoyang** [comment]
删除   来删除注释
