### ISSUE TITLE
what should I do?please help me!!

### ISSUE THREAD

**Issue by 1334224591** [huluoyang/freecodecamp.cn#121]
Challenge [Record Collection](https://freecodecamp.cn/challenges/record-collection#?solution=%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse%28JSON.stringify%28collection%29%29%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20update%28id%2C%20prop%2C%20value%29%20%7B%0Aif%28id%3D%3D5439%29%0A%20%20%20%20collection%5Bid%5D.pop%28value%29%3B%0A%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0Aupdate%285439%2C%20%22artist%22%2C%20%22ABBA%22%29%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
if(id==5439)
    collection[id].pop(value);

  return collection;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");


```

**Comment by huluoyang** [comment]
`update(5439, "artist", "ABBA");`只是测试用例，实际传入的参数是变化的。
所以你在函数中要判断是形参，而不是实参。
思路就是3个判断语句。
如果value不为空且id在collection中能找到，prop属性在对象中也能找到，那么更新对应的value。
如果value不为空且id在collection中能找到，但prop属性在对象中找不到，那么追加value到prop。
如果value为空，删除对应的prop属性。

**Comment by 1334224591** [comment]
@huluoyang 我一开始也是这样认为的，我就写了这样

**Comment by 1334224591** [comment]
function update(id, prop, value) {
    /_If value is non-blank (value !== "") and prop is not "tracks" then update or set the value for the prop._/
  collection.id.prop="";
            if (value !== "" && prop != "tracks") {
                collection.id.prop= value;
            }
            /_If the prop is "tracks" and value is non-blank, push the value onto the end of the tracks array._/
            else if (prop == "tracks" && value !== "") {
                collection.id.value.push(value);
            }

```
        else if (value === "") {
            delete collection.id.prop;
        }
```

  return collection;
}
@huluoyang

**Comment by huluoyang** [comment]
形参是变量，是不能用.来访问属性的，只能使用变量。
关于这点题目已经说过，还不熟悉请去复习之前的课程。

```
function update(id, prop, value) {
  if(value){
    if(prop!=="tracks"){
      collection[id][prop]=value;
    }else{
      collection[id][prop].push(value);
    }
  }else{
    delete collection[id][prop];
  }
  return collection;
}
```
