### ISSUE TITLE
这个挑战设计有些不合理

### ISSUE THREAD

**Issue by rufeng2015** [huluoyang/freecodecamp.cn#122]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.cn/challenges/escape-sequences-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var myStr; // Change this line
myStr ="\\ \t \t \r \n"; 


```

这个挑战我花了至少30分钟，然后才写出来这个挑战的代码。
首先我在 "\"这个问题上花了20分钟，可能是因为我的粗心，没看清要求造成的。
其次在是难在 \t \t这个问题上，因为我把它写成了一个，你们设置是写成了2个。 我没有说你们设计这个题目不好，只是我感觉你们如果把 \t \t改成 \t 会让学习者更加容易理解。      感觉你们的付出。

**Comment by huluoyang** [comment]
非常感谢您的真实反馈。
此题已改为：<code>反斜杠 制表符 退格符 回车符 换行符</code>

**Comment by Imdaidai** [comment]
我无力吐槽！
`var myStr = "\\ \t \t \r \n"; // Change this line`
结果为错误？

显示结果为
`myStr = "\\ \t \t \r \n"`

？？？？？？
bug吗？

**Comment by huluoyang** [comment]
看清任务要求。
反斜杠 制表符 退格符 回车符 换行符。
上面的结果不符合要求，第3个位退格符，不是制表符。
