### ISSUE TITLE
i don't understand this answer right?

### ISSUE THREAD

**Issue by jiajinning** [huluoyang/freecodecamp.cn#123]
Challenge [Repeat a string repeat a string](https://freecodecamp.cn/challenges/repeat-a-string-repeat-a-string#?solution=var%20strs%3D%20''%3B%0Afunction%20repeat%28str%2C%20num%29%20%7B%0A%20%20%2F%2F%20repeat%20after%20me%0A%20%20if%28num%3C1%29%7B%0A%20%20%20%20return%20''%3B%0A%20%20%7D%0A%20for%28var%20i%20%3D0%3Bi%3Cnum%3Bi%2B%2B%29%7B%0A%20%20%20strs%20%2B%3D%20str%3B%0A%20%7D%0A%20%20return%20strs%3B%0A%7D%0A%0Arepeat%28%22abc%22%2C%203%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var strs= '';
function repeat(str, num) {
  // repeat after me
  if(num<1){
    return '';
  }
 for(var i =0;i<num;i++){
   strs += str;
 }
  return strs;
}

repeat("abc", 3);

```

**Comment by huluoyang** [comment]
重要的事情说三遍，for 循环3次，每次叠加"abc"。
