### ISSUE TITLE
关于design-a-danmu-app的建议

### ISSUE THREAD

**Issue by imilu** [huluoyang/freecodecamp.cn#128]
这个项目的演示http://codepen.io/huluoyang/pen/GZbBwL

已经在`Settings`里提前引入了野狗的js，建议提示出来。
不然刚刚接触很容易懵圈= =。
还有在注释里面给出野狗的官方开发文档的地址，引导阅读。
这样对新手要要友好很多。

**Comment by huluoyang** [comment]
感谢反馈，已改进。
前面的课程部分对codepen已有简单介绍，稍微摸索一下就可了解。
此课程对于新手确实有些难，我也在考虑是否保留或调到中级项目。

**Comment by kerentang** [comment]
求教！我不明白这一层`<div class="dm_mask"></div>` 有什么意义？求指导，我自己就少一层，但是由于js代码写不出来导致只有一个弹幕墙，没有功能。。。
