### ISSUE TITLE
 is p element's problem?

### ISSUE THREAD

**Issue by geekhac** [huluoyang/freecodecamp.cn#130]
Challenge [Nest an Anchor Element within a Paragraph](https://www.freecodecamp.cn/challenges/nest-an-anchor-element-within-a-paragraph#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.gdgdocs.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Ca%20href%3D%22http%3A%2F%2Fwww.freecatphotoapp.com%22%3Ecat%20photos%3C%2Fa%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22%2Fimages%2Frelaxing-cat.jpg%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3E%E5%9C%A8%E5%A4%A7%E5%AE%B6%E5%BF%83%E7%9B%AE%E4%B8%AD%EF%BC%8C%E7%8C%AB%E6%98%AF%E6%85%B5%E6%87%92%E7%9A%84%E5%8F%AF%E7%88%B1%E7%9A%84%E5%8C%96%E8%BA%AB%EF%BC%8C%E5%AE%83%E5%8F%AF%E4%BB%A5%E7%9D%A1%E9%A5%B1%E4%BA%86%E5%86%8D%E8%B5%B7%E6%9D%A5%E5%90%83%E9%A5%AD%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%97%E8%B6%A3%E5%B0%8F%E8%80%97%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8D%96%E5%BE%97%E4%BA%86%E8%90%8C%EF%BC%8C%E4%BD%BF%E5%BE%97%E4%BA%86%E5%9D%8F%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%99%BE%E5%8F%98%E7%9A%84%E5%B0%8F%E6%80%AA%E5%85%BD%E5%B0%B1%E9%9B%86%E7%BB%93%E5%9C%A8%E4%B8%80%E5%8F%AA%E5%AE%A0%E7%89%A9%E4%B8%8A%EF%BC%8C%E6%80%8E%E8%83%BD%E4%B8%8D%E6%83%B9%E4%BA%BA%E6%80%9C%E7%88%B1%E3%80%82%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%E5%85%BB%E5%8A%A8%E7%89%A9%E6%9C%89%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E5%B0%B1%E6%98%AF%E4%BB%8B%E4%BA%8E%E7%88%B1%E4%B8%8E%E6%81%A8%E4%B9%8B%E9%97%B4%EF%BC%8C%E5%BD%93%E4%BD%A0%E9%92%A6%E7%BE%A1%E5%88%AB%E4%BA%BA%E8%90%8C%E5%AE%A0%E8%BF%99%E4%B9%88%E5%8F%AF%E7%88%B1%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E4%BD%A0%E4%B8%80%E5%AE%9A%E6%B2%A1%E6%9C%89%E6%83%B3%E8%BF%87%EF%BC%8C%E7%8B%97%E7%8B%97%E5%92%8C%E7%8C%AB%E7%8C%AB%E4%BC%9A%E5%88%B0%E5%A4%84%E6%8B%89%E5%B1%8E%EF%BC%8C%E7%94%9A%E8%87%B3%E4%BC%9A%E5%B1%AF%E8%80%81%E9%BC%A0%EF%BC%8C%E5%95%83%E9%9E%8B%E5%AD%90%EF%BC%8C%E7%94%A8%E7%88%AA%E5%AD%90%E7%88%AC%E9%97%A8%EF%BC%8C%E4%BD%A0%E4%B8%8D%E7%90%86%E5%AE%83%EF%BC%8C%E5%AE%83%E5%B0%B1%E6%8C%A0%E4%BD%A0%EF%BC%8C%E4%BD%A0%E8%A6%81%E5%AF%B9%E5%AE%83%E5%8F%91%E8%84%BE%E6%B0%94%EF%BC%8C%E5%AE%83%E4%BC%9A%E6%AF%94%E4%BD%A0%E6%9B%B4%E6%9D%A5%E5%8A%B2%E3%80%82%E6%89%80%E4%BB%A5%EF%BC%8C%E7%8B%97%E7%8C%AB%E6%85%8E%E5%85%A5%EF%BC%8C%E6%B2%A1%E6%9C%89%E4%B8%80%E5%AE%9A%E7%9A%84%E5%87%86%E5%A4%87%EF%BC%8C%E5%88%87%E5%8B%BF%E9%9A%8F%E4%BE%BF%E5%8E%BB%E4%BE%8D%E5%85%BB%E5%8A%A8%E7%89%A9%E3%80%82%E5%AE%83%E4%BB%AC%E4%B8%80%E6%97%A6%E8%AE%A4%E5%AE%9A%E4%BD%A0%E4%BA%86%EF%BC%8C%E4%BD%A0%E5%B0%B1%E6%98%AF%E5%AE%83%E4%BB%AC%E7%9A%84%E4%B8%BB%E4%BA%BA%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%BD%A0%E6%8A%9B%E5%BC%83%E5%AE%83%E4%BB%AC%EF%BC%8C%E5%AE%83%E4%BB%AC%E5%BF%85%E5%AE%9A%E5%BF%83%E4%B8%AD%E9%87%8D%E5%88%9B%E3%80%82%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

<a href="http://www.freecatphotoapp.com">cat photos</a>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by huluoyang** [comment]
感谢反馈。
删除 `<a href="http://www.freecatphotoapp.com">cat photos</a>` 即可。
页面只需保留一个a元素。

**Comment by Tomas-lee-git** [comment]
我也遇到相同的问题了，原来是这个原因，谢谢！

**Comment by zhaoyanqj** [comment]
删除 了<a href="http://www.freecatphotoapp.com">cat photos</a> 。也还是不行
报三个错
1你需要有一个链接到"http://www.freecatphotoapp.com"的a元素。
2你的a元素应该嵌套在你新的p元素中。
3你的p元素应该包含文本"View more "，注意more后面有一个空格。

**Comment by geekhac** [comment]
删除单独的a元素，不要删除p里面的a元素

**Comment by ArKinGitHub** [comment]
删除单独的a元素不行呀, 会报错"需要有一个链接到"http://www.freecatphotoapp.com"

**Comment by huluoyang** [comment]
看清题目要求，在现有的a元素外面包裹一个p元素。

不是让你创建一个新的a元素。

**Comment by 1126507455** [comment]
完美解决，谢谢大家

**Comment by alicemengruo** [comment]
完美解决
