### ISSUE TITLE
my exercise

### ISSUE THREAD

**Issue by cosin2077** [huluoyang/freecodecamp.cn#133]
<html>
<head>

<style>
h1{color:red;}
p{color:blue;}

</style>

</head>
<body bgcolor="yellow" >

 <button class="btn btn-block btn-primary">Like</button>
  <button class="btn btn-block btn-info">Info</button>

<h1 align="center">this is heading</h1>

<ins>
<h2>this is heading</h2>
</ins>

<del>
<h3>this is heading</h3>
</del>

<p>this is paragraph</p>

<hr/>

<p>this is paragraph</p>

<hr/>

<pre>预文本格式，就会保留空格 和换行

。</pre>

<code>computer code</code>
<br/>
<kbd>keyboard input</kbd>
<br/>
<tt>teletype text<tt>
<br/>
<var>computer variable</var>

<hr/>

<br/>
<br/>

<a href="#tip">跳转到书签</a>
<address>
请联系：<a href="mailto:conanskyforce@163.com">conanskyforce</a>.<br>
网址：<br/>
conan.com<br/>
地址：北京市海淀区<br/>
中国，北京<br/>
</address>

<hr/>

<abbr title="characteristic">cha.</abbr>
<br/>
<acronym title="my people counts">mc</acronym>
<br/>

<hr/>

<p>下一行会从右往左输出</p>

<br/>
<bdo dir="rtl">我就要从右往左输出！</bdo>

<hr/>

长引用：

<blockquote>黄沙百战穿金甲，不破楼兰终不还，后宫佳丽三千人，铁杵磨成绣花针。
</blockquote>

短引用：
<q>百年孤独</q>

<hr/>

<br/>

<a href="https://www.baidu.com"><img border="2px" src="https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/img/logo/bd_logo1_31bdc765.png" width="150px" length="150px"/></a>
<br/>
<a href="https://baidu.com" target="_blank">百度一下</a>
<a name="tip">这就是书签</a>

<hr/>

<a href="/index.html target="_top">跳出框架</a>
<br/>
<br/>
<a href="mailto:xxx@163.com?subject=Hello%20World!">发送邮件以Hello World!开头</a>
<br/>

<p>
这是另一个 mailto 链接：
<a href="mailto:someone@microsoft.com?cc=someoneelse@microsoft.com&bcc=andsomeoneelse2@microsoft.com&subject=Summer%20Party&body=You%20are%20invited%20to%20a%20big%20summer%20party!">发送邮件！抄送，秘密抄送，主题＋内容</a>
</p>

<br/>

<hr/>

<p>
一幅图像：
<img src="https://fbcdn-photos-c-a.akamaihd.net/hphotos-ak-xpa1/v/t1.0-0/s526x395/13669564_120208005080341_764307048512916358_n.jpg?oh=8eee5e06042c8af101203d39f08d931d&oe=583543AA&__gda__=1478536317_141aae154a2e4bdc9f6b76d9bbd7bffb" width="263" height="395"/>
</p>

<p>
另一幅图像动图：
<img src="http://www.w3school.com.cn/i/eg_cute.gif" width="100" length="100"/>
</p>

<p><big>我是<img src="https://ss2.baidu.com/6ONYsjip0QIZ8tyhnq/it/u=1350522371,812707229&fm=80" align="middle"/>文字</big></p>

<p><b>图在<img src="http://www.w3school.com.cn/i/eg_cute.gif" width="50" length="50" align="left">左边</b></p>

<p><b>图在<img src="http://www.w3school.com.cn/i/eg_cute.gif" width="50" length="50" align="right">右边</b></p>

<br/>

<p>调整图像大小</p>

<img src="http://www.w3school.com.cn/i/eg_mouse.jpg" width="50" length="50"><br/>
<img src="http://www.w3school.com.cn/i/eg_mouse.jpg" width="100" length="100"><br/>
<img src="http://www.w3school.com.cn/i/eg_moue.jpg" width="200" length="200" alt="200*200大鼠标"><br/>

<p><b><big>我的Facebook</big></b><a href="https://www.facebook.com/" target="_blank"><img border="0" src="https://fbcdn-photos-c-a.akamaihd.net/hphotos-ak-xfa1/v/t1.0-0/s280x280/12928422_1214056028628879_8449750351515216335_n.jpg?oh=788f75364e7efc4cf576de49aa8a98d9&oe=58218627&__gda__=1479890604_def7abdf7a68463f0e5b6b5555439572"></a></p>

<hr/>

<h3>一列三列</h3>

<table border="2">
<tr>
<td>100</td>
<td>200</td>
<td>300</td>
</tr>
</table>

<br/>

<h3>两列三列</h3>

<table border="4">
<tr>
<td>100</td>
<td>200</td>
<td>300</td>
</tr>
<tr>
<td>100</td>
<td>200</td>
<td>300</td>
</tr>
</table>

<br/>

<h3>三列三列</h3>

<table border="6">
<tr>
<td>100</td>
<td>200</td>
<td>300</td>
</tr>
<tr>
<td>100</td>
<td>200</td>
<td>300</td>
</tr>
<tr>
<td>100</td>
<td>200</td>
<td>300</td>
</tr>
<br/>
</table>

<br/>
<br/>

<hr/>

<table border="1">
<caption>表格标题</caption>
<tr>
<td>row 1, cell 1</td>
<td>row 1, cell 2</td>
</tr>
<tr>
<td>&nbsp;</td>
<td>row 2, cell 2</td>
</tr>
</table>

<br/>

<table >

<tr>
<th>表头1</th>
</tr>
<tr>
<td>row 1, cell 1</td>
<td>row 1, cell 2</td>
</tr>
<tr>
<td>row 2, cell 1</td>
<td>row 2, cell 2</td>
</tr>
</table>

<table border="1">
<tr>
<td>
<p>这是一个段落。</p>
<br/>
<p>这是另一个段落。</p>
</td>
<td><p>这个单元包含一个表格：</p>

</td>
</tr>
<tr>
<td><p>这个单元包含一个列表：</p>
<ul>
<li>苹果</li>
<li>香蕉</li>
<li>菠萝</li>
</ul>
</td>
<td><p>HELLO</p></td>
</tr>
</table>

<br/>

<hr/>

<p>this is <br/>a break<br/>paragraph</p>

<hr/>

<a href="http://www.w3school.com.cn">this is a link</a>

<img src="https://camo.githubusercontent.com/588e8cda9e7ce26c171e641284826273d8bed7df/68747470733a2f2f666263646e2d70686f746f732d632d612e616b616d616968642e6e65742f6870686f746f732d616b2d787061312f762f74312e302d302f73353236783339352f31333636393536345f3132303230383030353038303334315f3736343330373034383531323931363335385f6e2e6a70673f6f683d3865656535653036303432633861663130313230336433396630386439333164266f653d3538333534334141265f5f6764615f5f3d313437383533363331375f3134316161653135346132653462646339663662373664396262643762666662" height="142"/>

</body>
</html>

**Comment by huluoyang** [comment]
这还是第一次有人给我发自己的练习作业哦^_^。
`<button class="btn btn-block btn-primary">Like</button>`这是bootstrap的内置样式。
一**列**三列 应为  一**行**三列。
