### ISSUE TITLE
issue report!

### ISSUE THREAD

**Issue by LanceLou** [huluoyang/freecodecamp.cn#134]
Challenge [No repeats please](https://www.freecodecamp.cn/challenges/no-repeats-please#?solution=var%20num%20%3D%200%3B%0Afunction%20permAlone%28str%29%20%7B%0A%20%20permutate%28str.split%28%22%22%29%2C0%2Ccallback%29%3B%0A%20%20return%20num%3B%0A%7D%0Afunction%20swap%28arr%2Ci%2Cj%29%7B%0A%20%20var%20temp%3B%0A%20%20temp%20%3D%20arr%5Bi%5D%3B%0A%20%20arr%5Bi%5D%20%3D%20arr%5Bj%5D%3B%0A%20%20arr%5Bj%5D%20%3D%20temp%3B%0A%7D%0Afunction%20permutate%28listArr%2Cstart%2Ccallback%29%7B%0A%20%20var%20i%2C%20length%20%3D%20listArr.length%3B%0A%20%20if%20%28start%20%3D%3D%3D%20listArr.length-1%29%0A%20%20%20%20%20%20callback%28listArr%29%3B%0A%20%20else%7B%0A%20%20%20%20%20%20for%28i%20%3D%20start%3B%20i%20%3C%20length%3B%20i%2B%2B%29%7B%0A%20%20%20%20%20%20%20%20%20%20swap%28listArr%2Cstart%2Ci%29%3B%0A%20%20%20%20%20%20%20%20%20%20permutate%28listArr%2Cstart%2B1%2Ccallback%29%3B%0A%20%20%20%20%20%20%20%20%20%20swap%28listArr%2Ci%2Cstart%29%3B%0A%20%20%20%20%20%20%7D%0A%20%20%7D%0A%7D%0Afunction%20callback%28arr%29%7B%0A%20%20if%28arr.join%28%22%22%29.match%28%2F%28.%29%5C1%2F%29%20%3D%3D%3D%20null%29%0A%20%20%20%20num%2B%2B%3B%0A%7D%0ApermAlone%28%22aabb%22%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var num = 0;
function permAlone(str) {
  permutate(str.split(""),0,callback);
  return num;
}
function swap(arr,i,j){
  var temp;
  temp = arr[i];
  arr[i] = arr[j];
  arr[j] = temp;
}
function permutate(listArr,start,callback){
  var i, length = listArr.length;
  if (start === listArr.length-1)
      callback(listArr);
  else{
      for(i = start; i < length; i++){
          swap(listArr,start,i);
          permutate(listArr,start+1,callback);
          swap(listArr,i,start);
      }
  }
}
function callback(arr){
  if(arr.join("").match(/(.)\1/) === null)
    num++;
}
permAlone("aabb");

```

The issue is when I get the right value and return it, the system tell me that I not pass it.

**Comment by huluoyang** [comment]
你的代码仅仅通过了第一个测试用例，后面都没有通过。
可参考：http://stackoverflow.com/questions/32282607/permutations-excluding-repeated-characters

**Comment by huluoyang** [comment]
@bastarder  建议你针对此题写下自己的解题思路。

**Comment by bastarder** [comment]
我是使用了穷举,比较笨,因为我当时没有想到什么好方法,下面是我的代码,你可以参考一下;

你此题没有通过是因为 你需要把所有的逻辑 包含在一个function中才可以通过;

```

function permAlone(str) {
  var num = 0;
  permutate(str.split(""),0,callback);
  return num;

  function callback(arr){
    if(arr.join("").match(/(.)\1/) === null)
      num++;
  }
  function swap(arr,i,j){
    var temp;
    temp = arr[i];
    arr[i] = arr[j];
    arr[j] = temp;
  }
  function permutate(listArr,start,callback){
    var i, length = listArr.length;
    if (start === listArr.length-1)
        callback(listArr);
    else{
        for(i = start; i < length; i++){
            swap(listArr,start,i);
            permutate(listArr,start+1,callback);
            swap(listArr,i,start);
        }
    }
  }
}

console.log(permAlone("aabb"));
```

以下是我的代码;

```
function permAlone(str) {
  var result = [];
  var originList = str.split('');

  transform('',originList);

  return result.filter(function(string) {
    return !string.match(/(.)\1+/g);
  }).length;

  function transform(ori,list){
    for(var i=0; i<list.length; i++){
      if(ori.length + 1 === originList.length){
        result.push(ori + list[i]);
      }else{
        transform(ori + list[i],splice(list,i));
      }
    }
  }

  function splice(list , index){
    var record = list.join('').split('');
    record.splice(index,1);
    return record;
  }

}
```

**Comment by LanceLou** [comment]
嗯嗯   谢谢各位了
