### ISSUE TITLE
我觉得我程序没问题，但是结果是错的

### ISSUE THREAD

**Issue by TimLiu1** [huluoyang/freecodecamp.cn#135]
Challenge [Profile Lookup](https://freecodecamp.cn/challenges/profile-lookup#?solution=%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0A%0A%0Afunction%20lookUp%28firstName%2C%20prop%29%7B%0A%20%20var%20a%20%3D%200%3B%0A%20%20var%20b%20%3D%200%3B%0Afor%28var%20i%20%3D%200%3B%20i%3Ccontacts.length%3Bi%2B%2B%29%7B%0A%20%20if%28contacts%5Bi%5D.firstName%20%3D%3D%20firstName%29%7B%0A%20%20%20%20%20a%20%3D%201%3B%0A%20%20%20%20if%28contacts%5Bi%5D.prop%29%7B%0A%20%20%20%20%20%20b%20%3D%201%3B%0A%20%20%20%20%20%20return%20contacts%5Bi%5D.prop%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%20%20%0A%20%20if%28a%20%3D%3D%3D%201%20%26%26%20b%20!%3D%201%29%7B%0A%20%20%20%20return%20%20%22No%20such%20property%22%3B%0A%20%20%7D%0A%20%20if%28a%20%3D%3D%3D%200%29%7B%0A%20%20%20%20return%20%20%22No%20such%20contact%22%3B%0A%20%20%7D%0A%20%20%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUp%28%22Akira%22%2C%20%22likes%22%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUp(firstName, prop){
  var a = 0;
  var b = 0;
for(var i = 0; i<contacts.length;i++){
  if(contacts[i].firstName == firstName){
     a = 1;
    if(contacts[i].prop){
      b = 1;
      return contacts[i].prop;
    }
  }
}

  if(a === 1 && b != 1){
    return  "No such property";
  }
  if(a === 0){
    return  "No such contact";
  }

// Only change code below this line

// Only change code above this line
}

// Change these values to test your function
lookUp("Akira", "likes");

```

**Comment by huluoyang** [comment]
详细错误请看测试部分。
代码评析：手动标记法的方式未免太繁琐，得转化下思路。
此题考查的是对数组对象的属性和属性值访问。

```
function lookUp(firstName, prop){
  for(var i=0;i<contacts.length;i++){
    if(contacts[i].firstName == firstName){
      return contacts[i][prop] || "No such property";
    }
  }
  return "No such contact"; 
}
```

**Comment by lihaoran111222** [comment]
.prop换成[prop]就能通过了.

**Comment by huluoyang** [comment]
是的，弄清楚为什么了吗？
你的方法是手动标记法，未免太繁琐。
但思路是正确的。
