### ISSUE TITLE
IDE测试成功 

### ISSUE THREAD

**Issue by softwarefaith** [huluoyang/freecodecamp.cn#137]
Challenge [Where do I belong](https://www.freecodecamp.cn/challenges/where-do-i-belong#?solution=function%20where%28arr%2C%20num%29%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20var%20sort%20%3D%20arr.sort%28function%20compare%28a%2Cb%29%7B%0A%0A%20%20%20%20%20%20%20%20return%20a%20%3E%3D%20b%3B%0A%0A%20%20%20%20%7D%29%3B%0A%20%20console.log%28%22sort%3D%22%2Bsort%29%3B%0A%20%20%20%20var%20i%3D%200%3B%0A%20%20%20%20for%28%20%3Bi%3Csort.length%3Bi%2B%2B%29%7B%0A%0A%20%20%20%20%20%20%20%20if%28num%3C%3Dsort%5Bi%5D%29%20%7B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%7D%0A%0A%0A%20%20%20%20return%20i%3B%0A%7D%0A%0Awhere%28%5B5%2C3%2C20%2C3%5D%2C%205%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function where(arr, num) {
  // Find my place in this sorted array.
  var sort = arr.sort(function compare(a,b){

        return a >= b;

    });
  console.log("sort="+sort);
    var i= 0;
    for( ;i<sort.length;i++){

        if(num<=sort[i]) {

            break;
        }

    }


    return i;
}

where([5,3,20,3], 5);

```

**Comment by huluoyang** [comment]
提交成功啊，没明白你遇到的问题。
代码简化如下：

```
function where(arr, num) {
  // Find my place in this sorted array.
  arr.push(num);
  arr.sort(function(a,b){
    return a-b;
  });
  return arr.indexOf(num);
}
where([5,3,20,3], 5);
```
