### ISSUE TITLE
How to own a translation task？

### ISSUE THREAD

**Issue by xxks-kkk** [huluoyang/freecodecamp.cn#14]
I am wondering how to own a translation task? I want to own "basic-ziplines.json" translation but I cannot directly modify the wiki. Could you please consider changing the access permissions for wikis?

**EDIT1:**  "各位感兴趣想参与翻译的可以在下方留言写上你想翻译的章节" How to do this?

Thanks much! :smile:

**Comment by huluoyang** [comment]
留言即可，写上你想翻译的章节。

**Comment by xxks-kkk** [comment]
请问是在哪里留言？这里么？ 我想own "basic-ziplines.json"

**Comment by huluoyang** [comment]
对啊，留言即可。已经给你添加了，简单的事情别想复杂了。

**Comment by xxks-kkk** [comment]
为什么不把wiki权限打开让大家直接修改呢？

**Comment by huluoyang** [comment]
抱歉啊，我第一次弄wiki，我以为默认是开的，不知道如何打开权限。

**Comment by xxks-kkk** [comment]
没关系。请看  https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by huluoyang** [comment]
非常感谢啊，呱呱，又学一招。

**Comment by xxks-kkk** [comment]
:smiley:
