### ISSUE TITLE
练习说我没有结束标记，不知道问题出在哪里

### ISSUE THREAD

**Issue by Jason830** [huluoyang/freecodecamp.cn#140]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.cn/challenges/inform-with-the-paragraph-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<h1>Hello World</h1>
<h2>我家的猫咪</h2>
<P>Hello Paragraph</P>
```

**Comment by huluoyang** [comment]
把P换成小写的p就可以了。

**Comment by Dexia** [comment]
遇到这种情况最好的办法就是重置了
