### ISSUE TITLE
chrome下challenges练习页键盘无法输入。

### ISSUE THREAD

**Issue by Arinu** [huluoyang/freecodecamp.cn#144]
使用chrome浏览器，版本 51.0.2704.103 m。
https://freecodecamp.cn/challenges页面下无法输入字母、数字、符号、空格，而回车键、Ctrl键则都可以使用。

**Comment by huluoyang** [comment]
我使用的chrom版本 51.0.2704.103 (64-bit)，
没有出现你所说的问题。
看下你的输入法是否出现了问题。

**Comment by Arinu** [comment]
抱歉，今天又可以了。
估计是浏览器除了点问题。 :-D
