### ISSUE TITLE
queue next stop what do ? 

### ISSUE THREAD

**Issue by qzmly100** [huluoyang/freecodecamp.cn#146]
#### FreeCodeCamp Issue template

To Use this Template:
- Fill out what you can
- Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese
#### Issue Description
- When Issue Happens
- Steps To Reproduce
#### Browser Information
- Browser Name, Version
- Operating System
#### Your Code

``` js
If relevant, paste all of your challenge code in here
```

**Comment by miyaliu666** [comment]
请问你问的是这个题目吗？

https://freecodecamp.cn/challenges/stand-in-line
