### ISSUE TITLE
[183] Stand in Line   在 提示文本queue(testArr, 10) 之后, myArr[4] 的值应该是 10 中   myArr[4]应该是testArr[4]

### ISSUE THREAD

**Issue by alan-zhou** [huluoyang/freecodecamp.cn#147]
Challenge [Stand in Line](https://freecodecamp.cn/challenges/stand-in-line#?solution=function%20queue%28arr%2C%20item%29%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20arr.push%28item%29%3B%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log%28%22Before%3A%20%22%20%2B%20JSON.stringify%28testArr%29%29%3B%0Aconsole.log%28queue%28testArr%2C%206%29%29%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log%28%22After%3A%20%22%20%2B%20JSON.stringify%28testArr%29%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function queue(arr, item) {
  // Your code here
  arr.push(item);
  return item;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by huluoyang** [comment]
恩，确实如此，多谢反馈。
你上面的代码应该修订如下：

```
function queue(arr, item) {
  // Your code here
  arr.push(item);
  return arr.shift();  // Change this line
}
```

**Comment by summer-l** [comment]
function queue(arr, item) {
  // Your code here
  arr.push(item);

  return arr.shift();  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 8)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));
