### ISSUE TITLE
Add Borders Around your Elements Complete

### ISSUE THREAD

**Issue by wbaxm2016** [huluoyang/freecodecamp.cn#149]
#### FreeCodeCamp Issue template

To Use this Template:
- Fill out what you can
- Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese
#### Issue Description
- When Issue Happens
- Steps To Reproduce
#### Browser Information
- Browser Name, Version
- Operating System
#### Your Code

border没有高度属性。

**Comment by huluoyang** [comment]
多谢反馈，确实如此。

已修订。^_^

**Comment by HelloInternet** [comment]
在这一章Add Borders Around your Elements中第一段，border的没有高度属性的错误还是没有修改过来

**Comment by huluoyang** [comment]
恩，确实如此，感谢楼上的MM热心反馈。
这一次必须要修改过来。
