### ISSUE TITLE
翻译出错，应该为两个数字之间数字之和。

### ISSUE THREAD

**Issue by koala91** [huluoyang/freecodecamp.cn#154]
Challenge [Sum All Numbers in a Range](https://www.freecodecamp.cn/challenges/sum-all-numbers-in-a-range#?solution=function%20sumAll%28arr%29%20%7B%0A%20%20return%201%3B%0A%7D%0A%0AsumAll%28%5B1%2C%204%5D%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function sumAll(arr) {
  return 1;
}

sumAll([1, 4]);

```

**Comment by huluoyang** [comment]
感谢反馈。
正确翻译应为：返回这两个数字和它们之间所有数字的和。
合 应为 和。
提示：数字之间 是 不包括数字本身的。
