### ISSUE TITLE
段落的文本为“hello paragragh”，通不过

### ISSUE THREAD

**Issue by 101piano** [huluoyang/freecodecamp.cn#155]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.cn/challenges/inform-with-the-paragraph-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A%3Cp%3Ehello%20paragragh%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<h1>Hello World</h1>
<h2>我家的猫咪</h2>
<p>hello paragragh</p>
```

**Comment by huluoyang** [comment]
hello 应为 Hello。
