### ISSUE TITLE
数组怎么用点操作符访问？

### ISSUE THREAD

**Issue by weetad** [huluoyang/freecodecamp.cn#156]
#### FreeCodeCamp Issue template

To Use this Template:
- Fill out what you can
- Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese
#### Issue Description

和数组一样，有两种方式访问对象属性，一个是点操作符(.)，一个是中括号操作符([])。

【Accessing Objects Properties with the Dot Operator】
#### Browser Information
- Browser Name, Version
- Operating System
#### Your Code

``` js
If relevant, paste all of your challenge code in here
```

**Comment by huluoyang** [comment]
多谢反馈，此处确实有误，感谢指出。

**Comment by huluoyang** [comment]
此题是按照[官方](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-the-dot-operator)翻译的，确实欠缺review，再次感谢指出。
