### ISSUE TITLE
“remainder 的值应该等于2 2”多了个”2“

### ISSUE THREAD

**Issue by tonyh2021** [huluoyang/freecodecamp.cn#157]
#### Issue Description

https://freecodecamp.cn/challenges/finding-a-remainder-in-javascript

`remainder 的值应该等于2 2`多了个`2`。
#### Browser Information

Chrome 52.0.2743.116 (64-bit)
MacBook Pro（Retina 显示屏，13 英寸，2015 年初期） 10.11.5 
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/5045178/17835684/0e84e3d0-67aa-11e6-99fb-6984cf628489.png)

**Comment by huluoyang** [comment]
感谢反馈，thanks。
