### ISSUE TITLE
发现一个BUG，答案是对的但是通不过

### ISSUE THREAD

**Issue by hongsonGor** [huluoyang/freecodecamp.cn#159]
Challenge [Steamroller](https://www.freecodecamp.cn/challenges/steamroller#?solution=var%20arr1%3D%5B%5D%3B%0Afunction%20steamroller%28arr%29%20%7B%0A%20%20%2F%2F%20I'm%20a%20steamroller%2C%20baby%0A%20%20for%28var%20i%3D0%3Bi%3Carr.length%3Bi%2B%2B%29%7B%0A%20%20%20%20if%28Array.isArray%28arr%5Bi%5D%29%3D%3D%3Dfalse%29%7B%0A%20%20%20%20%20%20arr1.push%28arr%5Bi%5D%29%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20steamroller%28arr%5Bi%5D%29%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20arr1%3B%0A%7D%0A%0Asteamroller%28%5B1%2C%20%5B2%5D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.8 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var arr1=[];
function steamroller(arr) {
  // I'm a steamroller, baby
  for(var i=0;i<arr.length;i++){
    if(Array.isArray(arr[i])===false){
      arr1.push(arr[i]);
    }
    else{
      steamroller(arr[i]);
    }
  }
  return arr1;
}

steamroller([1, [2], [3, [[4]]]]);

```

**Comment by huluoyang** [comment]
必须通过所以的测试用例。
可以参考下这个：http://blog.ilanyy.com/fcc/fcc-algor-Steamroller.html
