### ISSUE TITLE
这道题完全不理解什么意思，不知道要获得什么样的结果

### ISSUE THREAD

**Issue by lzcreate** [huluoyang/freecodecamp.cn#162]
Challenge [Word Blanks](https://freecodecamp.cn/challenges/word-blanks#?solution=function%20wordBlanks%28myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb%29%20%7B%0A%20%20var%20result%20%3D%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20%0A%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks%28%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result ="";
  // Your code below this line


  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

**Comment by y1yang0** [comment]
意思就是在函数内部让形参的字符串组成一个正常语序的句子

**Comment by huluoyang** [comment]
wordBlanks 直译为单词之间的空白，准译为填词造句。
dog 是名字，big 是形容词，ran 是动词，quickly 是副词。
把这四个参数拼接成一个完整的句子即可。
dog is big and ran quickly

**Comment by leighchan** [comment]
这题让四个字符变量相加，得出result变量，每个变量中间增加一个空格字符就可以了

**Comment by Bingtuu** [comment]
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
result =  myAdjective +' ' + myNoun + ' ' + myAdverb + ' ' + myVerb;
  return result;
}
wordBlanks("cat", "little", "hit", "slowly")

**Comment by huluoyang** [comment]
填词造句有这么难吗？
想想你学习中文是如何填词造句的。
一个道理，为何换成英文就不会了。

**Comment by JustGogoing** [comment]
不是填词造句难，是没理解题意。。
