### ISSUE TITLE
未找到全局变量 myVar

### ISSUE THREAD

**Issue by killuaer** [huluoyang/freecodecamp.cn#167]
Challenge [Local Scope and Functions](https://www.freecodecamp.cn/challenges/local-scope-and-functions#?solution=function%20myFunction%28%29%20%7B%0A%20%20%27use%20strict%27%3B%0A%20%20var%20myVar%3D12%3B%0A%20%20%0A%20%20console.log%28myVar%29%3B%0A%7D%0AmyFunction%28%29%3B%0Avar%20myVar%3D2%3B%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0Aconsole.log%28myVar%29%3B%0A%0A%2F%2F%20now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function myFunction() {
  'use strict';
  var myVar=12;

  console.log(myVar);
}
myFunction();
var myVar=2;
// run and check the console 
// myVar is not defined outside of myFunction
console.log(myVar);

// now remove the console log line to pass the test


```

可是我通过火狐浏览器F12的控制台调试，它能正确输出全局变量myVar的值

**Comment by huluoyang** [comment]
看注释的提示，未找到myVar全局变量 一项为❎。
说明找到了myVar全局变量。刷新浏览器，输入代码如下：

```
function myFunction() {
  'use strict';
  var myVar=12;

  console.log(myVar);
}
myFunction();
```

**Comment by killuaer** [comment]
我知道原因了，是我的英文不过关了，题目的要求是不在函数外定义全局变量，看来我该补习英语了，有什么好的建议么？多谢你的解答了。

**Comment by huluoyang** [comment]
我的英语也一般，没什么好的建议。
遇到不懂的单词就查字典，如果查字典还是不懂，就谷歌。

**Comment by fnknzzz** [comment]
这个是什么意思啊，完全不懂

**Comment by killuaer** [comment]
意思是，不要定义全局变量，只要方法里的局部变量，我的理解就是这样的。

**Comment by fnknzzz** [comment]
完全不知道怎么过,无论如何也过不了

**Comment by killuaer** [comment]
function myFunction() {
  'use strict';
  var myVar=12;

  console.log(myVar);
}
myFunction();
var myVar=2;
// run and check the console 
// myVar is not defined outside of myFunction
console.log(myVar);
// now remove the console log line to pass the test

上面是我之前不通过的代码，因为我定义了全局变量，但题目的要求是不定义全局变量
// myVar is not defined outside of myFunction 的意思是 myVar不应该在myFunction方法外定义
答案我就不告诉你了，好好翻译一下英文，答案就在里面
