### ISSUE TITLE
是格式不对吗？

### ISSUE THREAD

**Issue by Abigailxxd** [huluoyang/freecodecamp.cn#171]
Challenge [Fill in the Blank with Placeholder Text](https://freecodecamp.cn/challenges/fill-in-the-blank-with-placeholder-text#?solution=%3Ch1%3EMonkey%20code%20%E7%8C%B4%E5%93%A5%E7%8C%B4%E5%93%A5%3C%2Fh1%3E%0A%0A%3Ch2%3E%E4%BD%A0%E7%9C%9F%E4%BA%86%E4%B8%8D%E5%BE%97%3C%2Fh2%3E%0A%0A%3Ch2%3E%E9%87%91%E7%AE%8D%E6%A3%92%E5%9C%A8%E6%89%8B%3C%2Fh2%3E%0A%0A%3Cp%3E%E9%97%AE%E4%B8%96%E9%97%B4%E8%B0%81%E6%98%AF%E8%8B%B1%E9%9B%84%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<h1>Monkey code 猴哥猴哥</h1>

<h2>你真了不得</h2>

<h2>金箍棒在手</h2>

<p>问世间谁是英雄</p>

```

**Comment by Abigailxxd** [comment]
已懂，，，羞耻捂脸中

**Comment by huluoyang** [comment]
猴哥都会写代码，🐱也会哦。
