### ISSUE TITLE
Return Early Pattern for Functions 修改函数abTest当a或b小于0时，函数立即返回一个undefined并退出。

### ISSUE THREAD

**Issue by lilynt** [huluoyang/freecodecamp.cn#173]
Challenge [Return Early Pattern for Functions](https://freecodecamp.cn/challenges/return-early-pattern-for-functions#?solution=%2F%2F%20Setup%0Afunction%20abTest%28a%2C%20b%29%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%28a%3C0%20%7C%7C%20b%3C0%29%7B%0A%20%20%20%20return%20c%2B%22dfsf%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round%28Math.pow%28Math.sqrt%28a%29%20%2B%20Math.sqrt%28b%29%2C%202%29%29%3B%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest%28-2%2C2%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; Tablet PC 2.0; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; GWX:RESERVED; Shuame; LCJB; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
// Setup
function abTest(a, b) {
  // Only change code below this line
  if(a<0 || b<0){
    return c+"dfsf";
  }


  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(-2,2);

```

**Comment by huluoyang** [comment]
此题目要求你返回的是undefined。

```
  if(a<0 || b<0){
    return undefined;
  }
```
