### ISSUE TITLE
姓名至少有三个字符不符合中国国情，两个字的名字通不过

### ISSUE THREAD

**Issue by danerlt** [huluoyang/freecodecamp.cn#177]
Challenge [Constructing Strings with Variables](https://freecodecamp.cn/challenges/constructing-strings-with-variables#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Avar%20ourName%20%3D%20%22Free%20Code%20Camp%22%3B%0Avar%20ourStr%20%3D%20%22Hello%2C%20our%20name%20is%20%22%20%2B%20ourName%20%2B%20%22%2C%20how%20are%20you%3F%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myName%3D%22%E6%9D%8E%E6%BB%94%22%3B%0Avar%20myStr%3D%22My%20name%20is%20%22%2BmyName%2B%22%20and%20I%20an%20swell!%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
// 举例
var ourName = "Free Code Camp";
var ourStr = "Hello, our name is " + ourName + ", how are you?";

// Only change code below this line
var myName="李滔";
var myStr="My name is "+myName+" and I an swell!";



```

**Comment by huluoyang** [comment]
编程中推荐用英文或拼音，而不是中文。
因为如果使用中文就需要切换输入法，并不利于编程。

```
var myName = "litao";
```

**Comment by nobodxbodon** [comment]
+1 一般国内用户第一反应都是用中文名而不是拼音吧
而且, 中英混输有输入法支持, 比如搜狗.
最后, 光因为切换输入法而否定在编程中使用中文, 是不是太武断了? 注释文档呢? 中文命名类/方法/变量带来的可读性提升呢?
就上面的例子
```
var 姓名 = "李滔";
var 输出字符串 = "你好, 我叫" + 姓名 + ", 你好吗?";
```
看起来对新手会更友好吧?

**Comment by cosin2077** [comment]
@nobodxbodon 英语不会，学嘛。如果只是一味的想着怎么对新手友好，那对他们最友好的方式就是啥都不学，就没这么多麻烦了。英文本来就在编程领域占有绝对地位，如果按照你这思路，他们一旦习惯中文编程，以后不知道还会遇到多少的坑。

**Comment by nobodxbodon** [comment]
@conanskyforce 
- 遇到坑不应该绕过去. 填上它才是对后人负责.
- 这个issue和学英语没有关系. 字符串的内容不支持中文就是个bug
