### ISSUE TITLE
关于证书的问题

### ISSUE THREAD

**Issue by earforth** [huluoyang/freecodecamp.cn#180]
1.看介绍, 完成.com课程会得到证书, 完成.cn也会得到证书吗?
2.这证书在国外被认可, 在国内呢?

**Comment by huluoyang** [comment]
1、证书是一样的，都是英文证书。
2、LinkedIn是全球通行的，在国内也有分公司，不需要翻墙。
大点的互联网公司基本都认可，小的公司可能没听过LinkedIn，需要耐心解释一下。
只要HR不是新手，基本都知道LinkedIn。
