### ISSUE TITLE
Moode_.07@hotmail.com

### ISSUE THREAD

**Issue by Jaredahmed** [huluoyang/freecodecamp.cn#181]
#### FreeCodeCamp Issue template

To Use this Template:
- Fill out what you can
- Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese
#### Issue Description
- When Issue Happens
- Steps To Reproduce
#### Browser Information
- Browser Name, Version
- Operating System
#### Your Code

``` js
If relevant, paste all of your challenge code in here
```

**Comment by huluoyang** [comment]
请先描述清楚你的问题，否则别人无法帮助你。
