### ISSUE TITLE
我觉这题目或者解释器有问题。转义符完全无用

### ISSUE THREAD

**Issue by Imdaidai** [huluoyang/freecodecamp.cn#182]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.cn/challenges/escape-sequences-in-strings#?solution=var%20myStr%3B%20%2F%2F%20Change%20this%20line%0AmyStr%20%3D'%5C%5C%20%5Ct%20%5Ct%20%5Cr%20%5Cn'%3B%20%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var myStr; // Change this line
myStr ='\\ \t \t \r \n'; 



```

**Comment by Imdaidai** [comment]
返回的值永远等于 myStr ='\ \t \t \r \n'

**Comment by huluoyang** [comment]
多谢反馈。
此题考查的是转义字符。
题目要求生成：反斜杠 制表符 退格符 回车符 换行符 
上面的结果不符合题目要求，第3个应为退格符，而不是制表符。
