### ISSUE TITLE
规则#2: 用你喜爱的任何库来定制属于你自己的风格，实现下面的功能 

### ISSUE THREAD

**Issue by andurils** [huluoyang/freecodecamp.cn#183]
Challenge [Build a Tribute Page](https://freecodecamp.cn/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

功能 超链接 链接跳转是博客园的文章

**Comment by huluoyang** [comment]
此处英文是user story，但很多人听不懂这个词，所以我找了一篇文章来解释。
但我已经把user story 翻译成了功能，所以此链接稍有牵强。
感谢反馈，本着初学者友好原则，会去掉此链接。
