### ISSUE TITLE
怎么把freecodecamp.com的数据同步过来？ 都是github账户登陆的

### ISSUE THREAD

**Issue by MaxTan** [huluoyang/freecodecamp.cn#184]
#### FreeCodeCamp Issue template

To Use this Template:
- Fill out what you can
- Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese
#### Issue Description
- When Issue Happens
- Steps To Reproduce
#### Browser Information
- Browser Name, Version
- Operating System
#### Your Code

``` js
If relevant, paste all of your challenge code in here
```

**Comment by huluoyang** [comment]
感谢反馈服务器挂了，已修复。
你的中文社区学习进度已经超过英文社区，没有同步的必要了。
详情可以参考：https://github.com/huluoyang/freecodecamp.cn/wiki/dataAsync

**Comment by TechQuery** [comment]
@huluoyang Async 是“异步”吧……？

**Comment by huluoyang** [comment]
@TechQuery 在js中 async 是异步，sync 是同步。
但日常生活中的同步与js中的同步不是同一个意思。
这是语言陷阱，你明白就好。

**Comment by TechQuery** [comment]
@huluoyang 

这我知道，并行、串行嘛~

但很多 非 Web 的**数据同步软件** 都用 xxx-Sync 的形式~

**Comment by huluoyang** [comment]
这个脚本目前仅仅是把数据抓取到console。
去重和上传到数据库都是手工操作。
所以算不上数据同步。
如果你有兴趣可以来改进下这个脚本，做成真正的数据同步。

**Comment by TechQuery** [comment]
@huluoyang 可以 CN 这边加些 API，然后 PR 回上游，即使上游不接受，你这个工具的上传代码也好写~
