### ISSUE TITLE
显示不对？

### ISSUE THREAD

**Issue by zcehy** [huluoyang/freecodecamp.cn#185]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.cn/challenges/escape-sequences-in-strings#?solution=var%20myStr%3B%20%2F%2F%20Change%20this%20line%0AmyStr%3D%20%22%20%5C%5C%20%5Ct%20%5Cb%20%5Cr%20%5Cn%20%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 OPR/39.0.2256.71</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var myStr; // Change this line
myStr= " \\ \t \b \r \n ";


```

**Comment by huluoyang** [comment]
前面和后面应该没有空格。

**Comment by zcehy** [comment]
是的，谢谢你
