### ISSUE TITLE
Pig Latin

### ISSUE THREAD

**Issue by yyjazsf** [huluoyang/freecodecamp.cn#187]
#### FreeCodeCamp Issue template

[页面](https://freecodecamp.cn/challenges/pig-latin)

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese
#### Issue Description
- 任务描述极不完整
- 已存在的任务描述
  如果单词以元音开始，你只需要在词尾添加 "way" 就可以了。
- 测试用例却很完整的
  translate("california") 应该返回 "aliforniacay"。
  translate("paragraphs") 应该返回 "aragraphspay"。
  translate("glove") 应该返回 "oveglay"。
  translate("algorithm") 应该返回 "algorithmway"。
  translate("eight") 应该返回 "eightway"。

**Comment by huluoyang** [comment]
感谢反馈。
pig latin 指的是：故意颠倒英语字母顺序拼凑而成的行话。
1、把辅音字母移到词尾，添加ay。
2、如果单词以元音开头，词尾添加way。
任务描述是完整的，只有2个情况。

**Comment by yyjazsf** [comment]
translate("glove") 应该返回 "oveglay"。
请你解释这个

请仔细看百科，包括发音也算

**Comment by huluoyang** [comment]
a\e\i\o\u 为元音字母，其他均为辅音字母。
这和字母的发音没关系。
glove前2个字母均为辅音字母，移到末尾，添加ay，所以结果为：oveglay。
