### ISSUE TITLE
不知道错在哪？

### ISSUE THREAD

**Issue by htjlqp** [huluoyang/freecodecamp.cn#191]
Challenge [Quoting Strings with Single Quotes](https://freecodecamp.cn/challenges/quoting-strings-with-single-quotes#?solution=var%20myStr%20%3D%20%22%3Ca%20href%3D'http%3A%2F%2Fwww.example.com'%20target%3D%E2%80%98_blank%E2%80%99%3ELink%3C%2Fa%3E%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var myStr = "<a href='http://www.example.com' target=‘_blank’>Link</a>";
```

**Comment by huluoyang** [comment]
‘_blank’ 应为：'_blank'
看清题目要求：

```
var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';
```
