### ISSUE TITLE
代码通不过，

### ISSUE THREAD

**Issue by danerlt** [huluoyang/freecodecamp.cn#193]
Challenge [Generate Random Whole Numbers within a Range](https://www.freecodecamp.cn/challenges/generate-random-whole-numbers-within-a-range#?solution=%2F%2F%20%E4%B8%BE%E4%BE%8B%0Afunction%20ourFunction%28ourMin%2C%20ourMax%29%20%7B%0A%0A%20%20return%20Math.floor%28Math.random%28%29%20*%20%28ourMax%20-%20ourMin%20%2B%201%29%29%20%2B%20ourMin%3B%0A%7D%0A%0AourFunction%281%2C%209%29%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20randomRange%28myMin%2C%20myMax%29%20%7B%0A%0A%20%20return%20Math.floor%28Math.random%20*%20%28myMax%20-%20myMin%20%2B%201%29%29%20%2B%20myMin%20%3B%20%2F%2F%20Change%20this%20line%0A%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0Avar%20myRandom%20%3D%20randomRange%285%2C%2015%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
// 举例
function ourFunction(ourMin, ourMax) {

  return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;
}

ourFunction(1, 9);

// Only change code below this line.

function randomRange(myMin, myMax) {

  return Math.floor(Math.random * (myMax - myMin + 1)) + myMin ; // Change this line

}

// Change these values to test your function
var myRandom = randomRange(5, 15);

```
# 

这里是fcc关于这道题的wiki
Q: Create a random whole number between 2 (inclusive, min) and 6 (inclusive, max) i.e. create a random whole number between min (inclusive) and max (inclusive)

A: Math.floor(Math.random() \* (6 - 2 + 1)) + 2

**Comment by earforth** [comment]
return Math.floor(Math.random \* 
random和*之间你写掉了括号

**Comment by huluoyang** [comment]
Math.random是一个方法，不是一个属性。
所以调用一个方法应为：Math.random()，而不是：Math.random。
