### ISSUE TITLE
my code shows me that the result is 6,but it supposes to be 1,why?

### ISSUE THREAD

**Issue by TailessCat** [huluoyang/freecodecamp.cn#194]
Challenge [Pairwise](https://freecodecamp.cn/challenges/pairwise#?solution=function%20pairwise%28arr%2C%20arg%29%20%7B%0A%20%20var%20x%3D%5B%5D%3B%0A%20%20%20%20%20%20if%28arr.length%3D%3D%3D0%29%7B%0A%20%20%20%20%20%20return%200%3B%0A%20%20%20%20%20%20%7D%0A%20%20for%28var%20i%3D0%2Clength1%3Darr.length%3Bi%3Clength1%3Bi%2B%2B%29%7B%0A%0A%20%20%20%20%0A%20%20%20%20if%28i%3D%3Dlength1-1%29%7B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%20%20for%28var%20j%3Di%2B1%2Clength2%3Dlength1%3Bj%3Clength2%3Bj%2B%2B%29%7B%0A%20%20%20%20%20%20if%28arr%5Bi%5D%2Barr%5Bj%5D%3D%3Darg%29%7B%0A%20%20%20%20%20%20%20%20x.push%28i%29%3B%0A%20%20%20%20%20%20%20%20x.push%28j%29%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20x.reduce%28function%28a%2Cb%29%7B%0A%20%20%20%20return%20a%2Bb%3B%20%7D%29%3B%0A%7D%0A%0Apairwise%28%5B1%2C%201%2C%201%5D%2C%202%29%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function pairwise(arr, arg) {
  var x=[];
      if(arr.length===0){
      return 0;
      }
  for(var i=0,length1=arr.length;i<length1;i++){


    if(i==length1-1){
      break;
    }
    for(var j=i+1,length2=length1;j<length2;j++){
      if(arr[i]+arr[j]==arg){
        x.push(i);
        x.push(j);
      }
    }
  }
  return x.reduce(function(a,b){
    return a+b; });
}

pairwise([1, 1, 1], 2);
```

**Comment by huluoyang** [comment]
测试用例中有2个没通过，这2个都是有相同元素。
也就是说代码中没考虑到这种元素相同情况。
pairwise([1, 1, 1], 2) 分解开来 1+1=2；对应的索引为：0+1=1；第三个1找不到匹配项，所以丢弃。
最终结果返回：1。
对应题意：每个工程师只能找一个设计师，一旦找到，这2个人就应从数组中排除掉。
