### ISSUE TITLE
the example webpage does not fully work ,maybe API service expired

### ISSUE THREAD

**Issue by Unclebellic** [huluoyang/freecodecamp.cn#198]
Challenge [Show the Local Weather](https://freecodecamp.cn/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.

this is the example: http://codepen.io/huluoyang/full/bedeBR/

And the page also does not match with some requirements asked in the video .

But I think I can finish the work anyway ,this is not that serious.

: )

**Comment by huluoyang** [comment]
这只是一个范例，免费接口份额用完了。
你自己找个API就行了，网上一大堆。
