### ISSUE TITLE
challenges/target-elements-by-id-using-jquery 未翻译完全

### ISSUE THREAD

**Issue by haobug** [huluoyang/freecodecamp.cn#199]
#### Issue Description
- When Issue Happens
  https://www.freecodecamp.cn/challenges/target-elements-by-id-using-jquery
- Steps To Reproduce
  1. visit  https://www.freecodecamp.cn/challenges/target-elements-by-id-using-jquery
  2. 左下角的验证细节没有翻译
#### Browser Information
- Browser Name, Version
  Chrome 45
- Operating System
  windows 7

**Comment by huluoyang** [comment]
未翻译就是给你留的机会，快快翻译然后PR给我。详情看Wiki
