### ISSUE TITLE
challenges/delete-your-jquery-functions 未翻译完全

### ISSUE THREAD

**Issue by haobug** [huluoyang/freecodecamp.cn#200]
问题同 #199 ，当然发现影响其他不大。
链接： https://www.freecodecamp.cn/challenges/delete-your-jquery-functions

**Comment by haobug** [comment]
接后续几个题目都是同样的问题，
有的题目需要需要把左边栏的滚动条向下卷动

**Comment by huluoyang** [comment]
左边栏的滚动条如果超过可视范围，肯定要拖动。
否则就不叫滚动条了。
tests部分的翻译重要性不高，不影响答题。
你可以尝试来翻译，再PR给我哦。
