### ISSUE TITLE
Finders Keepers

### ISSUE THREAD

**Issue by yyjazsf** [huluoyang/freecodecamp.cn#203]
#### Issue Description

[原文](https://freecodecamp.cn/challenges/finders-keepers)
测试用例错误
find([1, 3, 5, 8, 9, 10], function(num) { return num % 2 === 0; }) 应该返回 8
### 期望结果

应该返回[8,10]

**Comment by huluoyang** [comment]
非常感谢你的反馈。
题意要求只返回第一个符合条件的值8，而不是一个数组[8,10]。
但此处的翻译确实很生硬，基本是直译。
我会来修改，欢迎提交Issue。
