### ISSUE TITLE
cloud9需要有信用卡才能注册,很是不方便

### ISSUE THREAD

**Issue by earforth** [huluoyang/freecodecamp.cn#204]
如题

**Comment by huluoyang** [comment]
新版的C9确实如此，很麻烦。
其实就是个免费的ubuntu服务器，你可以自行购买个VPS主机，然后装ubuntu。
或者尝试SAE、阿里云、腾讯云等。
希望对你有帮助。
后续我找到靠谱的替代方案再告诉你。
