### ISSUE TITLE
I think my solution is right

### ISSUE THREAD

**Issue by hunterqy** [huluoyang/freecodecamp.cn#209]
Challenge [Reverse Arrays with reverse](https://freecodecamp.cn/challenges/reverse-arrays-with-reverse#?solution=var%20array%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%5D%3B%0Avar%20newArray%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20%E5%8F%AA%E8%83%BD%E5%9C%A8%E8%BF%99%E4%B8%80%E8%A1%8C%E4%B8%8B%E9%9D%A2%E5%86%99%E4%BB%A3%E7%A0%81%0Aarray.reverse%28%29%3B%0AnewArray%20%3D%20array%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var array = [1,2,3,4,5,6,7];
var newArray = [];

// 只能在这一行下面写代码
array.reverse();
newArray = array;

```

**Comment by earforth** [comment]
你的代码没问题, 试试reset按钮?

**Comment by huluoyang** [comment]
代码正确，我这里测试能通过。
建议你点击reset，再试下。
