### ISSUE TITLE
做题界面 因错误代码卡住后无法恢复

### ISSUE THREAD

**Issue by TechQuery** [huluoyang/freecodecamp.cn#212]
### 【故障详述】

特别在一些 **循环结构**相关的题目中，学员没写好 **循环退出条件**，导致 **答案代码**试运行时产生 **死循环**。

因为[代码预览功能](//github.com/huluoyang/freecodecamp.cn/blob/dev/server/views/challenges/showHTML.jade#L54)基于 `<iframe />` 实现，其程序执行与父页面同在主线程，必然卡住整个做题页。

若答案代码已保存，再次进入该题页面，代码预览自动执行又会卡住，学员就无法修改代码……
### 【初步方案】

@FreeCodeCamp-Chengdu 微信群有学员遇到该问题后，@Yasic 提出 ——

> 在浏览器设置中“禁用 JavaScript”，再重新进入该页修改代码
### 【完善方案】

虽然上述方案解决了那个学员的问题，但总归是个 **技巧性的临时方案**，改变现在 **做题、验证 UI 占用同一线程**才是长远良策。

故建议采用以下代码创建 **独立的代码预览窗口** ——

``` JavaScript
window.open('path/to/answerCode.html', '_blank', [
    'top=0',                         'left=' + window.innerWidth / 2,
    'height=' + window.innerHeight,  'width=' + window.innerWidth / 2,
    [
        'menubar',  'toolbar',  'location',  'status'
    ].join('=no,').slice(0, -1)
].join(','));
```

这不但能解决本问题，也能方便学员做“需要改变 ViewPort 大小”的 **响应式 UI** 题目~

**Comment by huluoyang** [comment]
您好，感谢您的这个提议。
新开一个窗口确实能规避卡住当前页的问题。
但难点在于：如何在不同的页面间传输数据？
进程间的通讯一直是一个难题，目前chrome能实现的也仅仅是消息提醒而已。

代码死循环这个问题每个人都曾经遇到。
这是每个人逃不掉的问题，必须要自己面对并解决。
只有自己被坑过，才会涨记性：写循环一定要注意边界条件。

FCC中涉及循环部分基本都在算法题，只有console，没有预览界面。
即使遇到死循环，刷新当前页即可重新修改代码，然后再运行。P.S 代码并不会自动运行。

当然这是我的个人观点，如果你遇到代码自动运行的情况请第一时间反馈给我。
thanks.

**Comment by TechQuery** [comment]
@huluoyang 

若不兼容 IE 8 及更老的浏览器，直接用 `postMessage()`、`onmessage` 即可，它们是 HTML 5 标准的 **跨页面/线程/进程通信** API，我也封装了一个[基于 jQuery 的 **跨网页双向通信插件**](//github.com/TechQuery/iQuery.js/blob/c1e0f23e0f896ad2d484ba6158bc5fc396568318/source/extension/iEvent.js#L145)~
