### ISSUE TITLE
Why can't use a switch statement?

### ISSUE THREAD

**Issue by Abigailxxd** [huluoyang/freecodecamp.cn#213]
Challenge [Record Collection](https://freecodecamp.cn/challenges/record-collection#?solution=%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse%28JSON.stringify%28collection%29%29%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Afunction%20update%28id%2C%20prop%2C%20value%29%20%7B%0A%0Aswitch%28id%2Cprop%2Cvalue%29%7B%0A%20%20%20%20case%20value!%3D%3D''%20%26%26%20prop!%3D%3D'tracks'%3A%0A%20%20%20%20%20%20collectionCopy%5Bid%5D%5Bprop%5D%3Dvalue%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20value!%3D%3D''%20%26%26%20prop%3D%3D%3D'tracks'%3A%0A%20%20%20%20%20%20collectionCopy%5Bid%5D%5Bprop%5D.push%28value%29%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20value%3D%3D%3D''%3A%0A%20%20%20%20%20%20delete%20collectionCopy%5Bid%5D%5Bprop%5D%3B%0A%20%20%7D%0A%0Areturn%20collection%3B%0A%7D%0A%0A%0A%0Afunction%20update%28id%2C%20prop%2C%20value%29%20%7B%0A%20if%28value!%3D%3D''%26%26prop!%3D%3D'tracks'%29%7B%0A%20%20%20collectionCopy%5Bid%5D%5Bprop%5D%3Dvalue%3B%0A%20%7Delse%20if%28value!%3D%3D''%26%26prop%3D%3D%3D'tracks'%29%7B%0A%20%20%20collectionCopy%5Bid%5D%5Bprop%5D.push%28value%29%3B%0A%20%7Delse%20if%28value%3D%3D%3D''%29%7B%0A%20%20%20delete%20collectionCopy%5Bid%5D%5Bprop%5D%3B%0A%20%7D%0A%20%0A%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0Aupdate%285439%2C%20%22artist%22%2C%20%22ABBA%22%29%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line

function update(id, prop, value) {

switch(id,prop,value){
    case value!=='' && prop!=='tracks':
      collectionCopy[id][prop]=value;
      break;
    case value!=='' && prop==='tracks':
      collectionCopy[id][prop].push(value);
      break;
    case value==='':
      delete collectionCopy[id][prop];
  }

return collection;
}



function update(id, prop, value) {
 if(value!==''&&prop!=='tracks'){
   collectionCopy[id][prop]=value;
 }else if(value!==''&&prop==='tracks'){
   collectionCopy[id][prop].push(value);
 }else if(value===''){
   delete collectionCopy[id][prop];
 }

 return collection;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");


```

**Comment by Abigailxxd** [comment]
第一次用了switch语句结果判错，第二次同样的思路用if/else语句结果判对，私以为思路相同为什么结果不同？求大神带飞~~~

**Comment by huluoyang** [comment]
if/else 是条件语句，switch是分支语句，二者并不能等同。

```
switch(prop){
    case 'tracks':
    do something
}
```

这两者适用在不同的场景。

**Comment by Abigailxxd** [comment]
学艺不精，，，拜谢
