### ISSUE TITLE
my way

### ISSUE THREAD

**Issue by qianqiangsam** [huluoyang/freecodecamp.cn#214]
Challenge [Where do I belong](https://freecodecamp.cn/challenges/where-do-i-belong#?solution=function%20where%28arr%2C%20num%29%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20var%20a%3Darr.push%28num%29%3B%0Aarr.sort%28function%28a%2Cb%29%7B%0A%20%20%20%20return%20a-b%3B%7D%29%3B%0A%20var%20b%3Darr.indexOf%28num%29%3B%0A%20%20return%20b%3B%0A%7D%0A%0Awhere%28%5B40%2C%2060%5D%2C%2050%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function where(arr, num) {
  // Find my place in this sorted array.
  var a=arr.push(num);
  arr.sort(function(a,b){
     return a-b;
  });
 return arr.indexOf(num);
}

where([40, 60], 50);

```

**Comment by huluoyang** [comment]
代码没有问题，请重试。
