### ISSUE TITLE
命名是符合驼峰标记法的，但是无法通过

### ISSUE THREAD

**Issue by ghost** [huluoyang/freecodecamp.cn#215]
Challenge [Understanding Case Sensitivity in Variables](https://freecodecamp.cn/challenges/understanding-case-sensitivity-in-variables#?solution=%2F%2F%20Declarations%0Avar%20StUdLyCapVaR%3B%0Avar%20properCamelCase%3B%0Avar%20TitleCaseOver%3B%0A%0A%2F%2F%20Assignments%0ASTUDLYCAPVAR%20%3D%2010%3B%0APRoperCAmelCAse%20%3D%20%22A%20String%22%3B%0AtITLEcASEoVER%20%3D%209000%3B%0Avar%20studlyCapVar%20%3D%2010%2C%0A%20%20%20%20properCamelCase%20%3D%20%22A%20String%22%2C%0A%20%20%20%20titleCaseOver%20%3D%209000%3B%0A%20%20%20%20) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
// Declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Assignments
STUDLYCAPVAR = 10;
PRoperCAmelCAse = "A String";
tITLEcASEoVER = 9000;
var studlyCapVar = 10,
    properCamelCase = "A String",
    titleCaseOver = 9000;

```

**Comment by huluoyang** [comment]
先声明，再赋值。
看清注释和题目要求。
