### ISSUE TITLE
Question: Prioritize One Style Over Another #49 

### ISSUE THREAD

**Issue by Irisisme** [huluoyang/freecodecamp.cn#216]
Challenge [Prioritize One Style Over Another](https://freecodecamp.cn/challenges/prioritize-one-style-over-another#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%20%20.pink-text%20%7B%0A%20%20%20%20%20%20color%3A%20pink%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
    .pink-text {
      color: pink;
    }
  }
</style>
<h1 class="pink-text">Hello World!</h1>

```

and this is result:

![2016-09-20 1 36 54](https://cloud.githubusercontent.com/assets/17779323/18658888/2c05a2fe-7f39-11e6-83db-c1dd932d86ff.png)

i can't find out the wrong code, any body can help?

THX

**Comment by huluoyang** [comment]
```
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
</style>
<h1 class="pink-text">Hello World!</h1>
```

元素选择器、ID选择器、class选择器，搞清楚他们间的区别。

**Comment by Irisisme** [comment]
GET！谢谢！
