### ISSUE TITLE
哪里有问题

### ISSUE THREAD

**Issue by qianqiangsam** [huluoyang/freecodecamp.cn#217]
Challenge [Missing letters](https://freecodecamp.cn/challenges/missing-letters#?solution=function%20fearNotLetter%28str%29%20%7B%0A%20%20var%20b%3B%0Afor%28var%20i%3D0%3Bi%3Cstr.length%3Bi%2B%2B%29%0A%20%20%7B%0A%20%20%20%20if%28str.charCodeAt%28i%2B1%29-str.charCodeAt%28i%29!%3D1%29%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20b%3Dstr.charCodeAt%28i%29%3B%0A%20%20%20%20%20%20%20%20return%20String.fromCharCode%28b%2B1%29%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20%7D%0A%0A%20%20%0A%7D%0A%0AfearNotLetter%28%22abcdefghjklmno%22%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function fearNotLetter(str) {
  var b;
for(var i=0;i<str.length;i++)
  {
    if(str.charCodeAt(i+1)-str.charCodeAt(i)!=1)
      {
        b=str.charCodeAt(i);
        return String.fromCharCode(b+1);
      }
    else{
      return undefined;
    }

  }


}

fearNotLetter("abcdefghjklmno");

```

**Comment by huluoyang** [comment]
非常抱歉，这么晚才回复你。
琐事缠身，有时候一耽误就忘记了。
今天仔细review此题和你的代码，
逻辑很清楚，我也认为代码没问题。
但显然有部分测试没通过。
在线编辑器不利于源码调试，我是新建html文件，把js放入其中，再用chrome dev source 添加断点来调试，才发现问题所在的。
1、str.charCodeAt(i+1)  缺乏判断。
str.charCodeAt(i+1)-str.charCodeAt(i)!=1
str.charCodeAt(i+1) 可能为NaN，所以if条件永远为真。
2、return undefined 应该是在for循环外部，而不是内部。
下面是我的代码：

```
function fearNotLetter(str) {
  var result;
  for(var i=0;i< str.length;i++){
    if(str.charCodeAt(i+1) && str.charCodeAt(i) - str.charCodeAt(i+1) !== -1){
         result = String.fromCharCode(str.charCodeAt(i)+1);
        return result;
    }
  }
  return undefined;
}

fearNotLetter("bcd");
```
