### ISSUE TITLE
关于21点算法的实现

### ISSUE THREAD

**Issue by ghost** [huluoyang/freecodecamp.cn#218]
Challenge [Counting Cards](https://freecodecamp.cn/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc%28card%29%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20%E6%8F%90%E7%A4%BA%3A%20Only%20the%20last%20will%20display%0Acc%282%29%3B%20cc%283%29%3B%20cc%287%29%3B%20cc%28'K'%29%3B%20cc%28'A'%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var count = 0;

function cc(card) {
  // Only change code below this line


  return "Change Me";
  // Only change code above this line
}

// Add/remove calls to test your function.
// 提示: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

**Comment by ghost** [comment]
能不能提供源码以供参考。

**Comment by huluoyang** [comment]
理清题意，按句翻译，代码自动浮现。
cc(2); cc(3); cc(7); cc('K'); cc('A');  这只是测试，无需关注。
