### ISSUE TITLE
为什么做完第一个任务以后没反应呢？如何标记完成了

### ISSUE THREAD

**Issue by Kidsunny** [huluoyang/freecodecamp.cn#219]
Challenge [Say Hello to HTML Element](https://freecodecamp.cn/challenges/say-hello-to-html-element#?solution=%3Ch1%3EHellow%20World%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<h1>Hellow World</h1>
```

**Comment by huluoyang** [comment]
Hello World  而不是 Hellow World。
