### ISSUE TITLE
Stand in line

### ISSUE THREAD

**Issue by njueszzy** [huluoyang/freecodecamp.cn#220]
Challenge [Stand in Line](https://freecodecamp.cn/challenges/stand-in-line) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function queue(arr, item) {
  // Your code here
  var te=arr.push(item);

  return te.shift( );  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

but when  I run this test, the website tells me that the te.shift is not a function. I want to know where is the problem.

**Comment by Shawydu** [comment]
@njueszzy Hi, the Array.push() method will return the new length of the array which the new object is pushed in. So in your case, 'te' is an integer number, it definitely doesn't have any properties like array

**Comment by njueszzy** [comment]
ok ,if I want to get an array,  I just need to say arr.push(item), and don't need to store it into a variable. Is it right?@Shawydu

**Comment by Shawydu** [comment]
That's right.

**Comment by huluoyang** [comment]
你们都是老外么？英语666
代码可以简化：

```
function queue(arr, item) {
  // Your code here
  arr.push(item);

  return arr.shift( );  // Change this line
}
```

**Comment by Shawydu** [comment]
不是，哈哈

**Comment by njueszzy** [comment]
其实我以为你是老外，哈哈

**Comment by huluoyang** [comment]
偶尔说两句英文还是可以的。
欢迎大家多来这里逛逛。
