### ISSUE TITLE
fcc的练习285：

### ISSUE THREAD

**Issue by whilewon** [huluoyang/freecodecamp.cn#225]
Challenge [Where do I belong](https://www.freecodecamp.cn/challenges/where-do-i-belong#?solution=function%20where%28arr%2C%20num%29%20%7B%0A%20%20console.log%28%22%E6%9C%80%E5%88%9D%E6%95%B0%E7%BB%84%22%29%3B%0A%20%20console.log%28arr%29%3B%0A%20%20arr.unshift%28num%29%3B%0A%20%20arr.sort%28function%28a%2Cb%29%7B%0A%20%20%20%20if%28a-b%3E0%29%7B%0A%20%20%20%20%20%20return%201%3B%0A%20%20%20%20%7Delse%20if%28a-b%3D%3D%3D0%29%7B%0A%20%20%20%20%20%20return%200%3B%0A%20%20%20%20%7Delse%7B%0A%20%20%20%20%20%20return%20-1%3B%0A%20%20%20%20%7D%0A%20%20%7D%29%3B%0A%20%20var%20itWhere%3D-1%3B%0A%20%20%0A%20%20for%28var%20i%3D0%3Bi%3Carr.length%3Bi%2B%2B%29%7B%0A%20%20%20%20if%28arr%5Bi%5D%3D%3Dnum%29%7B%0A%20%20%20%20%20%20%20%20itWhere%3D%20i%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%2F*arr.filter%28function%28val%2Cindex%29%7B%0A%20%20%20%20%20if%28num%3D%3Dval%29%7B%0A%20%20%20%20%20%20%20%20itWhere%3D%20index%3B%0A%20%20%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%20%7D%0A%20%20%7D%29%3B*%2F%0A%20%20%0A%20%20console.log%28%22%E6%9C%80%E7%BB%88%E6%95%B0%E7%BB%84%22%29%3B%0A%20%20console.log%28arr%29%3B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20console.log%28itWhere%29%3B%0A%20%20%0A%20%20return%20where%3B%0A%7D%0Awhere%28%5B10%2C%2020%2C%2030%2C%2040%2C%2050%5D%2C%2030%29%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function where(arr, num) {
  console.log("最初数组");
  console.log(arr);
  arr.unshift(num);
  arr.sort(function(a,b){
    if(a-b>0){
      return 1;
    }else if(a-b===0){
      return 0;
    }else{
      return -1;
    }
  });
  var itWhere=-1;

  for(var i=0;i<arr.length;i++){
    if(arr[i]==num){
        itWhere= i;
        break;
     }

  }

  /*arr.filter(function(val,index){
     if(num==val){
        itWhere= index;
        return true;
     }
  });*/

  console.log("最终数组");
  console.log(arr);
  // Find my place in this sorted array.
  console.log(itWhere);

  return where;
}
where([10, 20, 30, 40, 50], 30);
```

在codepen中的运行结果和本习题结果一致。请看 [这是codepen的运行代码](http://codepen.io/whilewon/pen/ALqQyZ?editors=1111),可以查看console结果

**Comment by huluoyang** [comment]
```
function where(arr,num){
   arr.push(num);    // 追加
   arr.sort(function(a,b){  //排序
      return a-b;
   });
   return arr.indexOf(num);  //查找
}
```
