### ISSUE TITLE
怎么给图片加a元素？（例子里是给文本加的）

### ISSUE THREAD

**Issue by liuyunpengg** [huluoyang/freecodecamp.cn#228]
Challenge [Link to External Pages with Anchor Elements](https://www.freecodecamp.cn/challenges/link-to-external-pages-with-anchor-elements）

**Comment by HarryZen** [comment]
图片标签前加<a>

**Comment by alovesnow** [comment]
`<a href="">``<img src=""/>``</a>`

**Comment by huluoyang** [comment]
理解标签的语义化，img是图片，a是超链接。
如何给图片添加超链接？
在超链接里嵌套图片即可。
把这句话翻译成英文，代码就出来了。
