### ISSUE TITLE
profile lookup

### ISSUE THREAD

**Issue by njueszzy** [huluoyang/freecodecamp.cn#229]
Challenge [Profile Lookup](https://www.freecodecamp.cn/challenges/profile-lookup#?solution=%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0Afunction%20lookUp%28firstName%2C%20prop%29%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20for%28var%20i%3D0%3Bi%3Ccontacts.length%3Bi%2B%2B%29%0A%20%20%7B%0A%20%20%20%20if%28firstName%20%3D%3D%20contacts%5Bi%5D.firstName%20%26%26%20contacts%5Bi%5D%5Bprop%5D%29%20%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20return%20contacts%5Bi%5D%5Bprop%5D%3B%20%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20else%20if%28firstName%3D%3Dcontacts%5Bi%5D.firstName%20%26%26%20!contacts%5Bi%5D%5Bprop%5D%29%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Breturn%20%22No%20such%20property%22%3B%0A%20%20%20%20%20%20%20%20%7D%20%0A%20%20%20%20%20else%20%0A%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%22No%20such%20contact%22%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUp%28%22Harry%22%2C%20%22likes%22%20%20%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 SE 2.X MetaSr 1.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

`````` javascript
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];
function lookUp(firstName, prop){
// Only change code below this line

  for(var i=0;i<contacts.length;i++)
  {
    if(firstName == contacts[i].firstName && contacts[i][prop]) 
        {
         return contacts[i][prop]; 
        }
        else if(firstName==contacts[i].firstName && !contacts[i][prop])
                {return "No such property";
        } 
     else 
     {
          return"No such contact";
        }
     }


// Only change code above this line
}

// Change these values to test your function
lookUp("Harry", "likes"  );

```in this task, the code is above, and  I don't get the first and second and third target,but when i try the Akira likes,i can get the right result,why?
and I have another question, how can i get the index of prop,
e.g
when I input the lastname.I can get the index of 1. thank you

``````

**Comment by huluoyang** [comment]
此问题已讲述多次，请自行查阅FCC问答。bbs.freecodecamp.cn

**Comment by njueszzy** [comment]
问题搞懂了，我想问一下怎么来获得第几个属性，比如输入likes,这是第4个属性，index=3,怎么获得index,谢谢

**Comment by huluoyang** [comment]
对象中的属性是无序的，并没有所谓的索引一说。
所以怎么获取index这个思路就是错误的。
详情参考这里：
https://bbs.freecodecamp.cn/topic/42/%E8%BF%98%E6%98%AFprofile-lookup%E7%9A%84%E7%96%91%E9%97%AE
