### ISSUE TITLE
翻译

### ISSUE THREAD

**Issue by yi2369** [huluoyang/freecodecamp.cn#230]
Challenge [Everything Be True](https://freecodecamp.cn/challenges/everything-be-true#?solution=function%20every%28collection%2C%20pre%29%20%7B%0A%20%20%2F%2F%20Is%20everyone%20being%20true%3F%0A%20%20for%20%28var%20i%3D0%3Bi%3Ccollection.length%3Bi%2B%2B%29%7B%0A%20%20%20%20if%20%28!collection%5Bi%5D%5Bpre%5D%29%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20true%3B%0A%7D%0A%0Aevery%28%5B%7B%22user%22%3A%20%22Tinky-Winky%22%2C%20%22sex%22%3A%20%22male%22%7D%2C%20%7B%22user%22%3A%20%22Dipsy%22%2C%20%22sex%22%3A%20%22male%22%7D%2C%20%7B%22user%22%3A%20%22Laa-Laa%22%2C%20%22sex%22%3A%20%22female%22%7D%2C%20%7B%22user%22%3A%20%22Po%22%2C%20%22sex%22%3A%20%22female%22%7D%5D%2C%20%22sex%22%29%3B%0Aevery%28%5B%7B%22user%22%3A%20%22Tinky-Winky%22%2C%20%22sex%22%3A%20%22male%22%2C%20%22age%22%3A%200%7D%2C%20%7B%22user%22%3A%20%22Dipsy%22%2C%20%22sex%22%3A%20%22male%22%2C%20%22age%22%3A%203%7D%2C%20%7B%22user%22%3A%20%22Laa-Laa%22%2C%20%22sex%22%3A%20%22female%22%2C%20%22age%22%3A%205%7D%2C%20%7B%22user%22%3A%20%22Po%22%2C%20%22sex%22%3A%20%22female%22%2C%20%22age%22%3A%204%7D%5D%2C%20%22age%22%29%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function every(collection, pre) {
  // Is everyone being true?
  for (var i=0;i<collection.length;i++){
    if (!collection[i][pre]){
      return false;
    }
  }
  return true;
}

every([{"user": "Tinky-Winky", "sex": "male"}, {"user": "Dipsy", "sex": "male"}, {"user": "Laa-Laa", "sex": "female"}, {"user": "Po", "sex": "female"}], "sex");

```

判断谓词（第二个参数）是否对一个集合（第一个参数）的所有元素都成立。
在汉语的环境里这句话不好理解，建议改成：判断谓词（第二个参数）在集合（第一个参数）的所有元素里都有效。

**Comment by huluoyang** [comment]
感谢你的反馈。
此题的翻译是英文的直译，确实很生硬。
我已重新翻译此题。
欢迎review。

**Comment by TechQuery** [comment]
@huluoyang 建议用 **Commit Message 指令**来关闭对应 Issue，既方便提出人 review，又利于日后 **追溯历史**~

**Comment by huluoyang** [comment]
@TechQuery   不懂如何使用 Commit Message 指令来关闭对应 Issue，求指教。
是因为我没有@具体人，直接回复的原因吗？

**Comment by TechQuery** [comment]
@huluoyang https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by huluoyang** [comment]
@TechQuery  感谢分享。
