### ISSUE TITLE
总是报错cannot read property ‘length’ of undefined，请问哪里错了？

### ISSUE THREAD

**Issue by liaow8** [huluoyang/freecodecamp.cn#231]
Challenge [Find the Longest Word in a String](https://freecodecamp.cn/challenges/find-the-longest-word-in-a-string#?solution=function%20findLongestWord%28str%29%20%7B%0A%20%20var%20arr%3Dstr.split%28%22%20%22%29%3B%0A%20%20var%20strMaxlength%3Darr%5B0%5D.length%3B%0A%20%20for%28var%20i%3D0%3Bi%3Carr.length%3Bi%2B%2B%29%7B%0A%20%20%20if%28strMaxlength%3Carr%5Bi%2B1%5D.length%29%7B%0A%20%20%20%20%20%20strMaxlength%3Darr%5Bi%2B1%5D.length%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20strMaxlength%3B%0A%7D%0A%0AfindLongestWord%28%22The%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function findLongestWord(str) {
  var arr=str.split(" ");
  var strMaxlength=arr[0].length;
  for(var i=0;i<arr.length;i++){
   if(strMaxlength<arr[i+1].length){
      strMaxlength=arr[i+1].length;
    }
  }
  return strMaxlength;
}

findLongestWord("The quick brown fox jumped over the lazy dog");

```

**Comment by huluoyang** [comment]
你的思路是对的，问题出在缺乏边界判断上。
当i=8时，arr[i+1] = arr[9]，数组已经越界，所以报错：undefined。
加个边界判断即可。

**Comment by liaow8** [comment]
谢啦！，解决该问题了
