### ISSUE TITLE
第9课貌似翻译有误，挑战是加注释，下面要求去掉注释

### ISSUE THREAD

**Issue by GoodERPJeff** [huluoyang/freecodecamp.cn#88]
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/1857069/15801033/a10e1090-2abb-11e6-8edd-9b6a0aeaf697.png)

**Comment by huluoyang** [comment]
非常感谢，翻译确实有误。
^_^   ^_^   ^_^
