### ISSUE TITLE
为何不直接Fork FreeCodeCamp/FreeCodeCamp

### ISSUE THREAD

**Issue by weibangtuo** [huluoyang/freecodecamp.cn#9]
当前的感觉不太好升级啊。如何让内容与 FreeCodeCamp/FreeCodeCamp一直同步？每次人工覆盖更新？

**Comment by huluoyang** [comment]
最初就是fork的，但是.com不支持中文翻译，还有很多资源无法访问问题，所以才单独开.cn分支。
.com课程内容时刻在变，我们会等新内容稳定后再翻译。

**Comment by weibangtuo** [comment]
嗯，现在也可以拉那边的更新，他们.com的commit还在，我尝试着拉他们的更新时候发现很多冲突而已。若人工更新不是个好办法，应该时不时rebase .com的代码，保持比较新的状态。

关于资源不能访问的问题，也是属于变更内容，fork他们的也会有很大的影响。fork他们的那.cn可以给.com贡献代码，因你保持commit结构，更新不受影响。该issue关闭。

**Comment by huluoyang** [comment]
fork .com 有太多限制，中文翻译这个事情2015年10月就有人做过，就是fork .com，最后不了了之。
具体你可以去看.com issue 搜索chinese。
因为国内情况极为特殊，很多东西必须再造，.com也不可能为国内花费巨大精力来改造。
所以只能靠自己。
因为缺乏独立精神造成翻译项目半途而废的事情太多了，
所以创立.cn

**Comment by huluoyang** [comment]
无论如何，你能提出这些问题说明你真正在思考这个翻译项目。
因此我决定把issue打开，让更多人看到这个讨论过程。

**Comment by weibangtuo** [comment]
若不打算合并到.com，是不需要fork的，fork可以给他们提交PR而已，不fork不受影响，但项目我觉得应该保持更新，比如他们release一次那我们就更新一次，或者定期更新，如每周更新一次。当前issue解决好更新问题就好，由于很多东西不一致，给.com贡献代码几乎不可能。

**Comment by huluoyang** [comment]
.cn是独立分支，是经过.com认可的。
其实我最初就是fork的，就是因为有冲突所以先绕过。
后期肯定会同步课程内容，再来解决冲突问题。
这里面有个优先级的问题，希望你能理解。

**Comment by huluoyang** [comment]
中文社区是独立分支，我会尽量保持一致。
这个问题今天正式关闭，不再做讨论。
