### ISSUE TITLE
我在Import a Google Font这一节碰到问题了~原因是中文版的作业里要我们引入的link的地址不对

### ISSUE THREAD

**Issue by wuxiaolan91** [huluoyang/freecodecamp.cn#94]
#### FreeCodeCamp Issue template

To Use this Template:
- Fill out what you can
- Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/chinese
#### Issue Description
- When Issue Happens
  当我在这个页面答题的时候一直报错。
  页面地址：
  https://freecodecamp.cn/challenges/import-a-google-font#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.gdgdocs.org%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3E%E5%9C%A8%E5%A4%A7%E5%AE%B6%E5%BF%83%E7%9B%AE%E4%B8%AD%EF%BC%8C%E7%8C%AB%E6%98%AF%E6%85%B5%E6%87%92%E7%9A%84%E5%8F%AF%E7%88%B1%E7%9A%84%E5%8C%96%E8%BA%AB%EF%BC%8C%E5%AE%83%E5%8F%AF%E4%BB%A5%E7%9D%A1%E9%A5%B1%E4%BA%86%E5%86%8D%E8%B5%B7%E6%9D%A5%E5%90%83%E9%A5%AD%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%97%E8%B6%A3%E5%B0%8F%E8%80%97%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8D%96%E5%BE%97%E4%BA%86%E8%90%8C%EF%BC%8C%E4%BD%BF%E5%BE%97%E4%BA%86%E5%9D%8F%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%99%BE%E5%8F%98%E7%9A%84%E5%B0%8F%E6%80%AA%E5%85%BD%E5%B0%B1%E9%9B%86%E7%BB%93%E5%9C%A8%E4%B8%80%E5%8F%AA%E5%AE%A0%E7%89%A9%E4%B8%8A%EF%BC%8C%E5%8F%AF%E7%8C%AB%E5%8F%AF%E7%8B%97%E3%80%82%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A
- Steps To Reproduce
  报错：commonFramework-0206e8352f.js:1 Refused to load the stylesheet 'https://fonts.gdgdocs.org/css?family=Lobster' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' _.gstatic.com *.googleapis.com *.bootstrapcdn.com https://_.bootstrapcdn.com _.cloudflare.com https://_.cloudflare.com 'self' ws://localhost:3001".
  后来litter的dandan告诉我说，是因为fcc的中文站里这个link的链接和fcc英文版的不一样，将link中href属性的值改为"https://fonts.googleapis.com/css?family=Lobster" 就能通过了
  我试了一下，问题果然好了。
  #### Browser Information
- Browser Name, Version
- Operating System
#### Your Code

<link href="https://fonts.gdgdocs.org/css?family=Lobster" rel="stylesheet" type="text/css">

<style>
  .red-text {
    color: red;
  }
  h2 {
    font-family: Lobster;
  }
  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，可猫可狗。</p>

<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

``` js
If relevant, paste all of your challenge code in here
```

**Comment by huluoyang** [comment]
多谢反馈。
因为谷歌字体在中国不可访问的原因，很多人又不会翻墙，所以改成gdg的字体。
但是测试部分没有修改，所以导致无法通过，已经修正。
thanks for your feedback

**Comment by wuxiaolan91** [comment]
好的。谢谢~

**Comment by wuxiaolan91** [comment]
怪不得我直接在浏览器打开谷歌字体连接的地址没问题呢。

**Comment by 1733094103** [comment]
我告诉你怎么做
<link href="https://fonts.gdgdocs.org/css?family=Lobster" rel="stylesheet" type="text/css">

<style>
  .red-text {
    color: red;
  }
  h2 {
    font-family: Lobster;
  }
  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，可猫可狗。</p>

<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
