### ISSUE TITLE
Please change issue URLS to direct to this repo, not Free Code Camp

### ISSUE THREAD

**Issue by BerkeleyTrue** [huluoyang/freecodecamp.cn#99]
We've got a couple of issues opened coming from this clone of Free Code Camp. Please change the appropriate files so they direct here.

This fork is months out of date and many issues here may have been fixed in the original Free Code Camp.

**Comment by huluoyang** [comment]
@BerkeleyTrue  Thanks for your feedback. I hava change the issues url.
I also will make this fork reacted to the origin.
